### ISSUE TITLE
No containers can be created

### ISSUE THREAD

**Issue by hasufell** [mhogomchungu/zuluCrypt#101]
more specifically, `zuluCrypt-cli --test` fails:

```sh
$ zuluCrypt-cli --test

WARNING: "loop" kernel module does not appear to be loaded,
tests and opening of encrypted containers in files will fail if the module was not built into the kernel

creating a testing image file
creating a testing image file
creating a testing image file
creating a keyfile
creating a keyfile

create a luks type volume using a key: FAILED
ERROR: Failed to create a volume
```

The warning appears to be wrong. `BLK_DEV_LOOP` is set to `y`.

**Comment by mhogomchungu** [comment]
I think "y" means the functionality is build into the kernel and "m" means the functionality is build as a loadable module.

You can get a list of currently loaded modules by running ```lsmod``` command from root's account.

Run the following command from root's account and post its result, i think your system has a problem with creating loop devices

```
losetup -f

```

**Comment by hasufell** [comment]
> Run the following command from root's account and post its result, i think your system has a problem with creating loop devices

No, I'm using losetup for other purposes already, which works perfectly. `BLK_DEV_LOOP` is built into the kerne.

**Comment by hasufell** [comment]
It appears this was a problem with `dm-crypt` module. Even `cryptsetup` only had partial working functionality.
