### ISSUE TITLE
zulucrypt-gui: wrong window type (floats in i3)

### ISSUE THREAD

**Issue by Piraty** [mhogomchungu/zuluCrypt#102]
## Description
`Version: 5.4.0`
`Qt 5.10.1`
Hi,
i'm using [i3wm](http://i3wm.org/) and experience non-intuitive and workflow-breaking behaviour with zulucrypt-gui.

I didn't do qt development before, but if you give a hint where to dig i could give it a try.

## Current behaviour
All windows appear floating, as if they are dialog boxes. Default would be to get tiled/stacked according to the WM's settings.
![screenshot_2018-10-02_23-01-53](https://user-images.githubusercontent.com/23238955/46376946-a8411900-c697-11e8-8abc-e1ae9bd59040.png)

## Expected behaviour
At least the initial volume manager should be handled as a normal window, i.e. be arranged/stacked according to WM's settings and not force floating mode on its own.
Other auxiliary dialogs like "open volume" etc. might float, which is not unexpected for some kinds of dialogs.

See as reference: https://faq.i3wm.org/question/61/forcing-windows-as-always-floating.1.html (inverted logic)
> (Michael) In case you feel that this window should not ever be tiling (in your case it seems to be a popup window indicating some progress), you could file a bugreport for the program you are using and tell them to set the correct window type on that window.

**Comment by mhogomchungu** [comment]
Are you using any other Qt GUI application, if yes, does it have the same problem zuluCrypt has or it behaves the way you expect it to.

**Comment by Piraty** [comment]
I use multiple qt5 applications, like keepassxc, quassel, octave. none of them has this issue and behaves like expected

**Comment by mhogomchungu** [comment]
This one is taking longer than expected.

I use PCLinuxOS and it does not have "i3wm" in its repository and this complicates things a bit since i will need to reproduce the issue to understand it.

My original plan was to install Ubuntu in VirtualBox and then install "i3wm" and test there but this process is a bit too long and i lacked the time to do it. WIll probably have enough time to look into this next weekend.

**Comment by Piraty** [comment]
no hurry man, i live with this for months now and can do a little longer.
Setting up a debian/ubuntu/voidlinux vm/qemu should take not much longer than 2h.
I advise for minimal debian+x+i3, but you would need to compile zulucrypt (which you are probably capable of ;) )
But void is easy too. after (minimal/network) install, `xbps-install zulucrypt-gui xorg i3`

**Comment by mhogomchungu** [comment]
I think i have found the problem, go this line[1] and replace ```Qt::WindowModal``` with ```Qt::NonModal``` and then recompile zuluCrypt.

[1] https://github.com/mhogomchungu/zuluCrypt/blob/346089dd6d8bc9be5e8aaeebdc7be99fe8be4ab9/zuluCrypt-gui/zulucrypt.ui#L6

Off-topic quest, why do you use this "i3"?. I install it on debian 9, logged in and nothing responds to clicks!, apparently, i have to run a terminal and run ```i3-msg exit``` to log out. i have to run a terminal and run a program to get application menu, 3 applications open and the windows of the applications becomes too narrow to use them effectively, i used fluxbox a long time ago and its first user experience is much, much better compared to i3.

**Comment by Piraty** [comment]
thanks for hinting to the code, i will give it a try.

Offtopic answer:
Sorry, i won't give you a guide "why and how to use i3", there's more than plenty on the net. For me it's just increasing productivity alot. What you were probably missing is mod+<num> to switch workspaces and a launcher like dmenu (but you can use anything else you like, just bind it to a keycombo in i3config).

**Comment by Piraty** [comment]
yeah, f0f80bb50ddcbeaa8b15cd41610824c5b6425e33 lets them float; thanks. 

A (very) minor issue is left though: having option "try icon" set leads to "minimize to try" instead of regular close (i know switching that option off leads to regular close). Can we have the tray icon and still be able to simply close the main window?

**Comment by mhogomchungu** [comment]
You can quit the app while the tray is on my pressing ```CTRL+Q``` while zuluCrypt window has focus. Will add an option to also quit the app while the tray is on when user click the window's close button.

**Comment by Piraty** [comment]
I know `ctrl+Q` is the default for most Xorg application to close (it's also noted in the `ZC` menu), but i3 users usually have something like `ctrl+shift+Q`. Using the latter, zulucrypt-gui just minimizes.

Thanks for considering the new option.

Btw. my intuitition in this regard is to "minimize to try" not by clicking "close" but instead by clicking "minimize"... if I were using a taskbar that would indicate running applications of course ;-)

**Comment by mhogomchungu** [comment]
The git version now has an option to close the application even when the tray icon is active.

![screenshot_20181109_111623](https://user-images.githubusercontent.com/3496115/48250971-28823900-e411-11e8-8aef-aaae558b21a2.png)
