### ISSUE TITLE
Opal 2.0 support

### ISSUE THREAD

**Issue by aardbol** [mhogomchungu/zuluCrypt#108]
Hi @mhogomchungu 

Thanks for your effort in creating such a handy tool!

I was wondering, if it would be possible to implement Open 2.0 support for hardware encryption. This way, we can make use of the hardware encryption that is builtin in a lot of SSDs nowadays. Is this technically possible?

https://github.com/Drive-Trust-Alliance/sedutil

**Comment by mhogomchungu** [comment]
I cant make head or tail of this "Opal" or of the "sedutil".

How can zuluCrypt use this "sedutil" util and how can i test it? I dont have whatever hardware it requires.

**Comment by aardbol** [comment]
Sorry, I don't have the means to test it anytime soon either. So perhaps it's more interesting to close this issue rather than to wait a month or longer to research it?

**Comment by mhogomchungu** [comment]
I'll keep it open hoping somebody else with the hardware will be willing to help out.

**Comment by aardbol** [comment]
Are you sure that's interesting? Opal 2.0 encryption is quite hard to manage on Linux and as you saw, sedutil is a very dead project.

I don't think Linux users give precedence to such an encryption mechanism since it's closed source and since there is plenty of hardware AES support in nowadays CPUs, the cost of implementing AES yourself is not expensive.

I'd like to see this feature in zulucrypt for easy management to start using it myself (since sedutil is not easy to use), but I don't think anyone will or can invest time into this soon.

**Comment by mhogomchungu** [comment]
Closing this one but i will keep an eye on it.

**Comment by git70** [comment]
Maybe we will just do a campaign of donations via BTC for financing and Francis will write a GUI for sedutil? :)
