### ISSUE TITLE
Audit planned?

### ISSUE THREAD

**Issue by zaggynl** [mhogomchungu/zuluCrypt#116]
Feature wise this looks absolutely awesome, is there an audit planned?
Edit: or is this stupid question as it's merely a frontend?

**Comment by mhogomchungu** [comment]
zuluCrypt is just a front end.

It uses cryptsetup to manage LUKS1, LUKS2 and PLAIN dm-crypt volumes.
It uses tcplay to manage TrueCrypt and VeraCrypt volumes.
It uses dislocker to manage Microsoft's bitlocker volumes.
