### ISSUE TITLE
Issues decrypting same file across different versions/machines

### ISSUE THREAD

**Issue by CreationTribe** [mhogomchungu/zuluCrypt#124]
First, you're amazing for keeping this going - so thank you.
I have ubuntu 18.10 on my desktop and 18.04 on my laptop. the version built for 18.10 handles everything perfect on m desktop. It works brilliantly. However, when I try to decrypt the same file on my laptop with the zc version for 18.04, it fails. I've checked md5sums to make sure there hasn't been any errors transferring the file - and there's not. There's a difference with the versions handling everything. What makes the builds so radically different. Can I install the zc built for 18.10 on my 18.04 machine? Or will that just not work?
Thanks again.

**Comment by mhogomchungu** [comment]
1. What version of zuluCrypt is in 18.10.
2. What version of zuluCrypt is in 18.04.

**Comment by CreationTribe** [comment]
It turns out, a re-install fixed it. *shrugs* I have no idea what happened. I md5sum checked both files, everything was cool. There should not have been any issues. But a re-install fixed everything. Sorry to trouble you :P And thanks.
