### ISSUE TITLE
zuluCrypt and zuluMount doesn't/can't list/mount /dev/nvme* devices

### ISSUE THREAD

**Issue by esotericDisciple** [mhogomchungu/zuluCrypt#125]
...Veracrypt can detect a PCIe-attached nvme/solid-state hard drive, though, for some reason. I can create and mount with Veracrypt, too, but Veracrypt doesn't make mount points like zuluCrypt/zuluMount can, and Manjaro deletes the /run/media/[mountpoint] directory after every reboot. So is there a way to get zuluCrypt/zuluMount to deal with mounting/unmounting the device instead?

**Comment by mhogomchungu** [comment]
Those are not supported devices and i have never seen them.

What is the full path to these devices in your system.

**Comment by esotericDisciple** [comment]
okay, I'll give it a try (sorry for the delayed post)

**Comment by esotericDisciple** [comment]
...It seems that I can now mount an encrypted /dev/nvme0n1p1 with zuluMount-gui and the device also shows on zuluCrypt-gui as a mountable volume. Thanks!

**Comment by mhogomchungu** [comment]
Thanks for the report
