### ISSUE TITLE
zulupolkit execution error

### ISSUE THREAD

**Issue by MegaLite** [mhogomchungu/zuluCrypt#127]
Debian  Linux testing august-2019, i3wm only installation (debootstrap). What package i should install for zulucrypt-gui be working?

**Comment by mhogomchungu** [comment]
What version of zuluCrypt is installed?

The problem maybe on a broken polkit system in your install. Open the
terminal and then run "polkit ls". Do you get a polkit prompt and does the
command run successfully after you enter the correct password?

**Comment by MegaLite** [comment]
I have installed zulucrypt* 5.4.0-3 i386 package (apt)

Maybe yes... `polkit Is` not found. Then run zuluCrypt-gui on terminal, got this with right password:

operator@debian:~$ zuluCrypt-gui 
==== AUTHENTICATING FOR org.zulucrypt.zulupolkit ===
Authentication is required to complete requested operation.
Authenticating as: operator
Password: 
==== AUTHENTICATION FAILED ===

**Comment by MegaLite** [comment]
What executables i need to proper run, and which deb package may contain it?

**Comment by mhogomchungu** [comment]
The problem is not with presence/lack of a particular executable but an improperly setup dbus session or polkit.

This problem is outside of zuluCrypt and is specific to your setup.
