### ISSUE TITLE
Consider adding big_writes option to ntfs-3g mounts

### ISSUE THREAD

**Issue by brendanhoar** [mhogomchungu/zuluCrypt#128]
In almost all use cases, when mounting NTFS volumes on linux utilizing the ntfs-3g fuse driver, adding the option "big_writes" leads to significantly better write performance.

Please consider adding it to the default flag set, or at least provide it as an option to select in the ZuluCrypt and ZuluMount GUI.

B

**Comment by mhogomchungu** [comment]
done[1].

This option seems to be ignored in my local test since it doesnt show up in mount options registered with "/proc/self/mountinfo"

[1] https://github.com/mhogomchungu/zuluCrypt/commit/672de4f5676fb26af72430d27fe12393193678c5

**Comment by brendanhoar** [comment]
From the ntfs-3g searches, It's active but for whatever reason, the setting is not passed back up the stack. I'll run some A/B tests when I get some time to pull and build.
