### ISSUE TITLE
Unable to restore header from LUKS2 container

### ISSUE THREAD

**Issue by git70** [mhogomchungu/zuluCrypt#133]
1. Create a LUKS2 volume with a built-in header.
2. Header backup.
3. The attempt to restore ends with the message: "Failed to perform requested operation".
Current version: 5.6.0.1569071478.a365c2ad-0
Linux Mint 19.2

**Comment by mhogomchungu** [comment]
Thanks for the report and the git version has a fix for the problem.

LUKS1 header are 3MB big and zuluCrypt had this size as the maximum size a volume header can have but LUKS2 header are 4MB big and zuluCrypt was rejecting them. I solved the problem by raising the maximum size to 10MB.
