### ISSUE TITLE
Plugins not available

### ISSUE THREAD

**Issue by git70** [mhogomchungu/zuluCrypt#136]
Scenario:
I open ZuluCrypt
I'm creating a container
I immediately go to the Open section
There are only two in the plugins menu: Internal Wallet and Gnome Keyring:
![screen1](https://user-images.githubusercontent.com/49098178/65897262-30dbbd80-e3af-11e9-96cd-a548f0ceb7c0.png)

After restarting the program, they are all available:
![screen2](https://user-images.githubusercontent.com/49098178/65897287-3c2ee900-e3af-11e9-86b9-361839a99196.png)

**Comment by mhogomchungu** [comment]
I don't know what to say about this one.

Lets attribute this to a lucky hit by a Neutrinos and call it a day.

Please reopen if you reproduce it again.

**Comment by git70** [comment]
This problem was not one-off ;)
Occurs every time.

**Comment by mhogomchungu** [comment]
Do you get a polkit prompt when you are creating your volume?

I just looked at the code and it doesnt show plugins when polkit backend is active.

**Comment by git70** [comment]
Yes - there is a polkit prompt for hard disk operations.
I just did the second test:
The above problem does not occur when creating the container file (no polkit prompt).

BTW: Maybe it's a coincidence with problem # 132?

**Comment by mhogomchungu** [comment]
Click ```menu->options->manage non system volumes``` and then add your hard drive to the list to suppress the polkit prompt and try again.

If you were getting a polkit prompt in that bug report then the problems could be related.

**Comment by git70** [comment]
Bingo!
Both problems (this one and # 132) are related!
But think about a more intuitive solution, because other users may have such problems in the future ...

**Comment by mhogomchungu** [comment]
The plugin system need to be rethought and i planned to do it but totally forgot about it. Disabling plugins when polkit is in use was supported to be a temporary solution.

**Comment by git70** [comment]
I sent an email to you yesterday. Did you check?

**Comment by mhogomchungu** [comment]
> I sent an email to you yesterday. Did you check?
>
> I did not reveice an email from you.

Writing this from my inbox.

**Comment by git70** [comment]
Maybe it went to spam?
I wrote to the address mhogomchungu at ...

**Comment by mhogomchungu** [comment]
I modified my comment above while were writing your response, please read it.

**Comment by git70** [comment]
Ok, everything is clear.
I'm waiting patiently...

**Comment by mhogomchungu** [comment]
This one is now fixed.

Thanks for the report.
