### ISSUE TITLE
How to resize .img files?

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [mhogomchungu/zuluCrypt#139]
Hi, I couldn't find anything on resizing .img files made by this application...shouldn't that be a feature by now?

**Comment by mhogomchungu** [comment]
The feature is not in because I never wanted to use the feature and nobody requested it.

Will look into it.

**Comment by esotericDisciple** [comment]
Okay, thanks. I'd very much appreciate it...

**Comment by mhogomchungu** [comment]
Sorry, not going to support this one, it will add too much complexity and i think this kind of operation should be left to tools that are dedicated to deal with partitions.

**Comment by neurodiverseEsoteric** [comment]
Well great now how am I supposed to backup a 100gb ZC file to a BDXL/M-Disc with a capacity of 93GB?
