### ISSUE TITLE
TrueCrypt keys dialog does not handle spaces in paths

### ISSUE THREAD

**Issue by dkaparis** [mhogomchungu/zuluCrypt#14]
In zuluCrypt select open->"plain, luks, truecrypt container in a file".
In the "open encrypted volume" dialog, for key type select "TrueCrypt keys".
The "TrueCrypt keys" dialog appears, where you can add key files with the "add keyfile" button.
It appears that any paths containing whitespace get discarded and only paths with no whitespace get applied correctly.

**Comment by mhogomchungu** [comment]
just fixed this bug here[1] and will appreciate if you can confirm that the bug is fixed.

thanks for the report.

[1] https://github.com/mhogomchungu/zuluCrypt/commit/a1a29d87ea2c00f60d425590a230141c972f94dd

**Comment by dkaparis** [comment]
Confirmed, the fix for latest git works for me.

Thanks,
Dimitri
