### ISSUE TITLE
Feature Request: Permissions hardening/options for FAT filesystem containers

### ISSUE THREAD

**Issue by GIJack** [mhogomchungu/zuluCrypt#142]
Feature request.

Give the options for setting fmask and dmask FAT filesystem options when mounting FAT formated containers. At very lease change the options away from the insecure defaults.

**Comment by mhogomchungu** [comment]
What options would you like to be used as defaults?

Its possible to set custom mount options based on file systems  and based on a file system that is in  a particular device..

How to set mount options based on file systems of  certain type:
1. Create a text file at ```/etc/zuluCrypt/generic_fs_options```.
2, In it, add ```vfat fmask=abc,dmask=def``` where "abc" and "def" are your preferred options.

ps:
"FAT" file system is usually reported as "vfat" so i have used "vfat" in my example. The entry for the file system you added above must match the file system blkid tool reported on the device for it to work.

How to set mount options based on a file system on a particular device.
1. Create a text file at ```/etc/zuluCrypt/fs_options```
2. In it, add ```UUID=XYZ fmask=abc,dmask=def``` where "XYZ" is the UUID of a file system on a device you want to customize its mount options, "abc" and "def" are your preferred mount options.

**Comment by GIJack** [comment]
fmask=0177
dmask=0077

Essentially only the user who mounted the partition can use it. will prevent a leak. Especially as GUI systems tend to be one user at a time.

The GUI should have a GUI option, the CLI should have switches.

**Comment by mhogomchungu** [comment]
The default mount point prefix in zuluCrypt is ```/run/media/privave/$USER/``` and there is a compile time switch to change it to ```/home/$USER```.

Only the person who created the mount point has access to these mount point prefixes. If a user want other people to gain access to the mount point, they can allow them by checking "share mount point" checkbox and an additional publicly sharable mount point will be created at 
```/run/media/public```

In summary, only you will have access to the mount point you created unless you explicitly allow others to access it.

**Comment by mhogomchungu** [comment]
Closing this one as "invalid". The permissions on the mount point are irrelevant because only the user who created the mount point has access to it.
