### ISSUE TITLE
Add support of encfs config file stored in arbitrary location

### ISSUE THREAD

**Issue by CoolSpot** [mhogomchungu/zuluCrypt#143]
By default EncFS reads config file named ".encfs6.xml" from the encrypted directory.
[Gnome Encfs Manager](https://moritzmolch.com/apps/gencfsm/index.html) allows user to use config file stored anywhere (Configure stash -> Advanced... -> encfs_config_file).
EncFS CLI accepts environment variable [ENCFS6_CONFIG](https://manpages.ubuntu.com/manpages/eoan/en/man1/encfs.1.html) for custom config file location.

This might be a safer approach for situation when EncFS is used over potentially vulnerable storage, such as Dropbox.

I can't see how I can make zuluMount to use EncFS config located in another directory.

**Comment by mhogomchungu** [comment]
Do you know about SiriKali?[1]. Its my project and it can already do what you want.

Will add the ability shortly.

[1] https://github.com/mhogomchungu/sirikali

**Comment by CoolSpot** [comment]
SiriKali looks good, thank you very much!
Even though it has option to use external config, it doesn't work well with EncFS version 1.9.2 because there was no "--config" flag before version 1.9.5 .
EncFS version 1.9.2 is the default version in Ubuntu 18.04 LTS and Linux Mint 19 repositories.

**Comment by mhogomchungu** [comment]
Latest[1] released version of SiriKali supports this. You can get a binary version of SiriKali from here[2] if you can't/don't want to build from source.

[1] https://github.com/mhogomchungu/sirikali/releases/tag/1.4.4

[2] https://download.opensuse.org/repositories/home:/obs_mhogomchungu/xUbuntu_18.04/amd64/
