### ISSUE TITLE
Missing -K parameter description in manpage

### ISSUE THREAD

**Issue by hhgoten** [mhogomchungu/zuluCrypt#144]
After long searching, I found :
https://github.com/mhogomchungu/zuluCrypt/wiki/zuluCryt-cli-howto
there is 
Explanations for the above options.
-K : this options takes user id of the person who is invoking the command. It is a 
     necessary option if the command is invoked using "sudo", "pkexec" or "su".

I missed the Parameter -K in manpage , so I made mistakes by using zuluCrypt-cli .
Maybe you can add it to the manpages.
Regards hhgoten

**Comment by mhogomchungu** [comment]
Done.

https://github.com/mhogomchungu/zuluCrypt/commit/7d6a3b80bd7b27f446b4f468eb25355c01cd21be
