### ISSUE TITLE
Error when installing Zulucrypt 5.7.1 on Ubuntu 18.04

### ISSUE THREAD

**Issue by alikhojah** [mhogomchungu/zuluCrypt#147]
Hi
I downloaded the binaries and then tried to install. I got this error:
*******
(Reading database ... 177953 files and directories currently installed.)
Preparing to unpack .../libzulucrypt1_5.7.1.1580795937.8f7e9895-0_amd64.deb ...
Unpacking libzulucrypt1:amd64 (5.7.1.1580795937.8f7e9895-0) ...
dpkg: error processing archive /home/ubuntu1804/التنزيلات/zuluCrypt-5.7.1-ubuntu-18.04-Bionic_Beaver/amd64/libzulucrypt1_5.7.1.1580795937.8f7e9895-0_amd64.deb (--install):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libzuluCrypt-exe.so.1.2.0', which is also in package libzulucrypt-exe1.2.0:amd64 5.4.0-2build1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Processing triggers for libc-bin (2.27-3ubuntu1.2) ...
Errors were encountered while processing:
 /home/ubuntu1804/التنزيلات/zuluCrypt-5.7.1-ubuntu-18.04-Bionic_Beaver/amd64/libzulucrypt1_5.7.1.1580795937.8f7e9895-0_amd64.deb
**********
Please advise
Thanks

**Comment by mhogomchungu** [comment]
You already have zuluCrypt installed from your distribution and both can not coexist because they use the same file names.

The solution is for you to remove all zuluCrypt packages you installed from your distribution and try again.

**Comment by alikhojah** [comment]
Thanks

I did and it works now fine

Regards


________________________________
