### ISSUE TITLE
Custom name for image and link to another folder

### ISSUE THREAD

**Issue by vladimircores** [mhogomchungu/zuluCrypt#148]
It would be great to have an option to give a custom name for mounted image and also create a link in selected path.
![Screen Capture_select-area_20200919204917](https://user-images.githubusercontent.com/442111/93686891-a4dc0d80-fab9-11ea-9398-21ff68f21e60.png)

**Comment by mhogomchungu** [comment]
What file manager are you using?

Making an encrypted volume usable is a two step process.

1. The encrypted volume is said to be unlocked when an encryption mapper is created at "/dev/dm-XYZ" and a link to it is created in "/dev/mapper".

2. The encryption/decryption mapper get mounted.

What happens here is that zuluCrypt unlocks the volume and then udisks sees the encryption mapper and ultimately, the encryption mapper shows up there in your file manager.

in zuluCrypt, you can customize the last component of the mount path and the encryption mapper path that shows up in "/dev/mapper" is unique per volume but the paths in "/dev/" are generic and can not be customized.

I see that you are using an image file and i think your file manager should be able to discover the name of the image file and show it there. I other words, this feature request should be made to your file manager.

There is nothing i can do here.
