### ISSUE TITLE
Capitalize text labels

### ISSUE THREAD

**Issue by jdoe0** [mhogomchungu/zuluCrypt#15]
Currently, most of the text labels in zuluCrypt's GUI are not capitalized. I think capitalizing text labels will make the GUI look more consistent with other applications.

**Comment by mhogomchungu** [comment]
I think i changed most of them with below commit,will fix the rest of them as i see them.

Thanks for your suggestion.

https://github.com/mhogomchungu/zuluCrypt/commit/9b966b75d3afc4392b9927f89af27a36f992a391
