### ISSUE TITLE
Feature Request: Window for Luks keyslot management

### ISSUE THREAD

**Issue by GIJack** [mhogomchungu/zuluCrypt#150]
I have a feature request. Under the Volumes sub menu for a Key Management window.

What I request:

> 
> The main part of the window will be a list of keyslots and information from cryptsetup luksDump. These will be presented as selectable items.
> 
> There will be button to delete specific keys based on slot selected.
> 
> There will be an "add" button that can add to a specific numbered slot, using the dialog from "Add a Key to the volume", but with another field for specifying slot number.

I have a key management scheme that uses numbered unique keys, that I will not have access to the key if it is lost or stolen, however, I will know which number key is lost, and will be able to remove it from the keyring, right now all on the command line.

It would make the management task a lot easier if this was easily done in the GUI.

**Comment by mhogomchungu** [comment]
Working on this but some information in luksDump wont be available because zuluCrypt uses cryptsetup through its library and the information is not exposed through the library API.

**Comment by mhogomchungu** [comment]
The CLI will produce an output like below and GUI will use the same info:

For LUKS2
```
[ink@localhost ~]$ zuluCrypt-cli -b -b -d luks2.img 
Slot Number: 0
Type: luks2
PBKDF type: argon2i
Cipher: aes-xts-plain64
Cipher key: 512 bits
Priority: Normal
Time cost: 0
Memory: 645039
Threads: 4

Slot Number: 1
Type: luks2
PBKDF type: argon2i
Cipher: aes-xts-plain64
Cipher key: 512 bits
Priority: Normal
Time cost: 0
Memory: 650852
Threads: 4

[ink@localhost ~]$ 

```

For LUKS1

```
[ink@localhost ~]$ zuluCrypt-cli -b -b -d luks1.img 
Slot Number: 0
Type: luks1
PBKDF type: pbkdf2
PBKDF hash: sha256
PBKDF iterations: 876734

Slot Number: 1
Type: luks1
PBKDF type: pbkdf2
PBKDF hash: sha256
PBKDF iterations: 879676

[ink@localhost ~]$ 

```

**Comment by mhogomchungu** [comment]
The git version now has this feature
![Screenshot_20201113_152116](https://user-images.githubusercontent.com/3496115/99072132-7e6fb580-25c4-11eb-943e-26c2112995ce.png)
![Screenshot_20201113_152151](https://user-images.githubusercontent.com/3496115/99072134-7fa0e280-25c4-11eb-8508-fa353feaf05d.png)
![Screenshot_20201113_152250](https://user-images.githubusercontent.com/3496115/99072143-829bd300-25c4-11eb-9d4f-fb94957a69e8.png)
![Screenshot_20201113_152327](https://user-images.githubusercontent.com/3496115/99072159-8b8ca480-25c4-11eb-9c32-cd236c97ac7b.png)
![Screenshot_20201113_152351](https://user-images.githubusercontent.com/3496115/99072169-8d566800-25c4-11eb-9571-a854df161910.png)

![Screenshot_20201113_152044](https://user-images.githubusercontent.com/3496115/99072126-7c0d5b80-25c4-11eb-9b25-43f1d49a25bd.png)

**Comment by GIJack** [comment]
This does in fact work. However, I do suggest being add button directly from the list dialog. Same dialog as now, just add a button from the list.

**Comment by mhogomchungu** [comment]
Try again. There is now a check box that makes it possible to show/hide inactive key slots and clicking inactive key slot will show a menu that can be used to add a key to that specific key slot.

Clicking active key slot will show a menu that given an option to delete a key in that specific key slot.

**Comment by GIJack** [comment]
OOh, interesting. I am looking at this now. UI looks great. thanks.

However there appears to be a slight bug. For some reason I am only able to delete a keyslot with the key in that slot. With my usage model, if I needed to delete a key it

to do this with cryptsetup, you need to use luksKillSlot, instead of luksRemoveKey

**Comment by mhogomchungu** [comment]
I did not know the behavior of luksKillSlot.

Try now.

The new behavior is as follows:-
1. luksRemoveKey behavior if slot number is NOT given.
2. luksKillSlot behavior if slot number is given.

**Comment by GIJack** [comment]
Works. Brilliant. Thanks again for adding this.
