### ISSUE TITLE
Problem mounting file after a major system update on Arch

### ISSUE THREAD

**Issue by taldarus** [mhogomchungu/zuluCrypt#151]
Sorry for the bit of newb post, but I prefer to post as soon as I find a problem, and I can't find a solution. It will be like 18 hours until I can really attack the problem on my end, and I would prefer not to wait and find out it isn't my end. 

Running on Arch.
Occasionally access two encrypted files that I use for storage.
Have used zulucrypt for a long time.

Just did a major linux update, and now zulucrypt isn't working afterwords. ( This is why I think the problem isn't on my end )
Correction, the program is working, but now I am getting a new problem with the mounting of the file ( I use the GUI ).

"Permission to access the volume was denied

or

the volume is not supported (LVM/MDRAID signatures found)"

**Comment by mhogomchungu** [comment]
Why closing without a reason?

I suspect the problem is because cryptsetup changed its library name and zulucrypt could not find it.

A solution is to recompile zulucrypt.
