### ISSUE TITLE
Version for Linux Mint 20.1 (i.e. Ubuntu 20.04)

### ISSUE THREAD

**Issue by git70** [mhogomchungu/zuluCrypt#153]
Hi

Will there be a special version for Ubuntu 20.04, is it safe to use 19.10?

Regards!

**Comment by mhogomchungu** [comment]
You can get them from here[1] and to be specific, download the following entries

1. https://download.opensuse.org/repositories/home:/obs_mhogomchungu/xUbuntu_20.04/amd64/libzulucrypt-dev_5.7.1.1606400885.67e25661-0_amd64.deb
2. https://download.opensuse.org/repositories/home:/obs_mhogomchungu/xUbuntu_20.04/amd64/libzulucrypt1_5.7.1.1606400885.67e25661-0_amd64.deb
3. https://download.opensuse.org/repositories/home:/obs_mhogomchungu/xUbuntu_20.04/amd64/zulucrypt-cli_5.7.1.1606400885.67e25661-0_amd64.deb
4. https://download.opensuse.org/repositories/home:/obs_mhogomchungu/xUbuntu_20.04/amd64/zulucrypt-gui_5.7.1.1606400885.67e25661-0_amd64.deb

I plan to make a new version this week or next week and for version 20.04 will be included in the main page when i do that.

[1] https://download.opensuse.org/repositories/home:/obs_mhogomchungu/xUbuntu_20.04/amd64/

**Comment by git70** [comment]
Thank you!
You are as reliable as ever!
