### ISSUE TITLE
conflicting keyboard shortcut for F: "&Favorites" and "Mount &Folder"

### ISSUE THREAD

**Issue by SimonHeimberg** [mhogomchungu/zuluCrypt#159]
The keyboard shortcut "Alt-F" in ZuluMount is used by two actions (in English language): "**F**avorites" and "Mount **F**older"
The result is both do not work.

Which one should be changed? Suggestions: "F**a**vorites" / "Fa**v**orites" / "Mount F**o**lder" / "Mount Folde**r**"

Note: also update all `<source>` strings in translations: translations/zuluMount/{ar_SA.ts, fr_FR.ts, de_DE.ts}

#### references:

**F**avorites:
https://github.com/mhogomchungu/zuluCrypt/blob/90aebf38b3d5eb8a035a698eb120e1a298c81b54/zuluMount-gui/zulumount.ui#L111

Mount **F**older:
https://github.com/mhogomchungu/zuluCrypt/blob/90aebf38b3d5eb8a035a698eb120e1a298c81b54/zuluMount-gui/zulumount.ui#L138

**Comment by mhogomchungu** [comment]
This is already fixed and i went with your suggestion of "Mount &Folder"

Thanks for the report.
