### ISSUE TITLE
Cryptsetup library not found

### ISSUE THREAD

**Issue by mystinen** [mhogomchungu/zuluCrypt#162]
Hi, I've installed zuluCrypt-6.0.0-ubuntu-20.04-Focal_Fossa.tar.xz following the steps in the README. It seems to all succeed... but launching zuluCrypt GUI gives the popup message: "Cryptsetup library could not be found and zuluCrypt will most likely not work as expected. Please recompile zuluCrypt to force it to re-discover the new library".

I braved an attempt at compiling, but step 3 of BUILD_INSTRUCTIONS fails with "Unable to locate package libgcrypt11-dev". This seems to be some now-deprecated 'transitional package' I do not know how to acquire...

Any advice appreciated to get zuluCrypt operational for mounting BitLocker volumes on Ubuntu 20.04.

[Some background: running KDE Neon 5.21/Ubuntu 20.04 [Focal]. The zuluCrypt package from the distribution is versioned 5.7.0, which fails to mount an external BitLocker drive, I _think_ because of [these issues](https://github.com/mhogomchungu/zuluCrypt/issues/109). So I'm attempting to install a newer version of zuluCrypt to leverage its use of cryptsetup (updated to version 2.3.3) instead of dislocker for mounting the BitLocker partition.]

Thanks for the great work!

**Comment by mhogomchungu** [comment]
The package name should be " libgcrypt20-dev"

That is a strange error if you have cryptsetup installed.

**Comment by mystinen** [comment]
Thanks @mhogomchungu, it built fine with the change of package name to libgcrypt20-dev. (I had also to make small obvious tweaks to _changelog_ and _control_ in 'debian'.) zuluCrypt now nicely mounts BitLocker drives!

> After dismissing the warning, does it still fail to mount the bitlocker volume?

Yes, if the warning was simply dismissed it failed to mount the BitLocker volumes. I don't recall the exact error message but it was something along the lines of "One or more parameters required to...".

**Comment by mhogomchungu** [comment]
The git version now does not show that pop up window
