### ISSUE TITLE
Bundled lxqt-wallet vs. upstream

### ISSUE THREAD

**Issue by imciner2** [mhogomchungu/zuluCrypt#163]
Is 6.0.0 know to work with the latest upstream release (3.2.1) of lxqt-wallet, or have other changes been made to the bundled copy that are not present in upstream.

I ask because Fedora is currently using the bundled copy of lxqt-wallet, but our system version is now 3.2.1 so we are looking at if we can unbundle it.

**Comment by mhogomchungu** [comment]
Unbundling it and using upstream version 3.2.1 should be perfectly fine.

**Comment by imciner2** [comment]
Thanks!
