### ISSUE TITLE
Creating volumes with yubikey

### ISSUE THREAD

**Issue by ossii79** [mhogomchungu/zuluCrypt#164]
I see there is a possibility to open encrypted disks/containers using yuibkey.
Is there also possible to create an encrypted container with yuibkey as 2nd factor from within zuluCrypt?

**Comment by mhogomchungu** [comment]
The functionality currently does not exist.

**Comment by mhogomchungu** [comment]
The git version can now create a volume using yubikey's challenge response feature.
