### ISSUE TITLE
unrecognized error 255

### ISSUE THREAD

**Issue by nickfreen** [mhogomchungu/zuluCrypt#169]
Hi. 
While creating a new truecrypt volume with ZuluCrypt version  5.4.0  in Debian Buster, I got a pop-up error message saying something like "unrecognized error 255" after the volume password entering. Nevertheless the volume has been successfully created: I can regularly open it with the given password.  
What that error means? Must I be worried about that? 

Thank you.

**Comment by mhogomchungu** [comment]
It means an error i did not anticipate to happen has happened. Why it happened is hard to tell and i suspect right after the creation process was completed, some other tool in your access accessed the device preventing zuluCrypt from further accessing it.

You should not worry about it and sorry for not responding sooner.
