### ISSUE TITLE
potential exposure of sensitive data in debug window

### ISSUE THREAD

**Issue by G0rd0n** [mhogomchungu/zuluCrypt#170]
I noticed that the debug window of Zulucrypt shows the location of previously used files.
Is it possible to provide an option to 'clear on exit'?
For some professions this visibility of the encrypted files may lead to the exposure of sensitive data.

**Comment by mhogomchungu** [comment]
The git version now add entries to the log window only for operations that took place while the log window is activated and i think this should be good enough.

Closing now as fixed but feel free to comment if you think this is not adequate.

**Comment by G0rd0n** [comment]
This seems like a very elegant solution :)
