### ISSUE TITLE
ZC 6 install on Debian buster fails

### ISSUE THREAD

**Issue by speefak** [mhogomchungu/zuluCrypt#171]
try to install ZC6 on Debian10 ( files : /zuluCrypt-6.0.0-debian-10-Buster/amd64/ ) :

sudo apt install ./libzulucrypt1_6.0.0.1611918130.9f984c69-0_amd64.deb 
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Hinweis: »libzulucrypt1« wird an Stelle von »./libzulucrypt1_6.0.0.1611918130.9f984c69-0_amd64.deb« gewählt.
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  libminiupnpc17 libnatpmp1
Verwenden Sie »sudo apt autoremove«, um sie zu entfernen.
Die folgenden NEUEN Pakete werden installiert:
  libzulucrypt1
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 104 nicht aktualisiert.
Es müssen noch 0 B von 127 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 420 kB Plattenplatz zusätzlich benutzt.
Holen:1 /home/user/Schreibtisch/Unbenannter Ordner/libzulucrypt1_6.0.0.1611918130.9f984c69-0_amd64.deb libzulucrypt1 amd64 6.0.0.1611918130.9f984c69-0 [127 kB]
(Lese Datenbank ... 253101 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../libzulucrypt1_6.0.0.1611918130.9f984c69-0_amd64.deb ...
Entpacken von libzulucrypt1:amd64 (6.0.0.1611918130.9f984c69-0) ...
dpkg: Fehler beim Bearbeiten des Archivs /home/user/Schreibtisch/Unbenannter Ordner/libzulucrypt1_6.0.0.1611918130.9f984c69-0_amd64.deb (--unpack):
 Versuch, »/usr/lib/x86_64-linux-gnu/libzuluCrypt-exe.so.1.2.0« zu überschreiben, welches auch in Paket libzulucrypt-exe1.2.0:amd64 5.4.0-3 ist
dpkg-deb: Fehler: »einfügen«-Unterprozess wurde durch Signal (Datenübergabe unterbrochen (broken pipe)) getötet
Fehler traten auf beim Bearbeiten von:
 /home/user/Schreibtisch/Unbenannter Ordner/libzulucrypt1_6.0.0.1611918130.9f984c69-0_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by mhogomchungu** [comment]
Can you change your language to english first because i do not understand that language.

**Comment by mhogomchungu** [comment]
Closing this one for lack of activity.
