### ISSUE TITLE
cli/gui doesnt see volumes in QEMU/VM due to missing /dev/vd* as allowed devices

### ISSUE THREAD

**Issue by pg2web** [mhogomchungu/zuluCrypt#172]
Both cli and gui dont see /dev/vd* QEMU/VM volumes attached via virtio, only when presented as sata - currently only /dev/sd* and /dev/hd* allowed.

Patch attached.
[zulucrypt-6.0.0-vdpatch.patch.txt](https://github.com/mhogomchungu/zuluCrypt/files/7582867/zulucrypt-6.0.0-vdpatch.patch.txt)

**Comment by mhogomchungu** [comment]
Done, thanks
