### ISSUE TITLE
 helpful hint about project visibility

### ISSUE THREAD

**Issue by stefanocudini** [mhogomchungu/zuluCrypt#173]
I suggest you create your own page on wikipedia because at this moment the official history of your tool is not clear, compared to the older truecrypt and the various veracrypt alternatives etc.
I found myself doing a search on the net to understand the landscape of encryption tools for linux.

I tried zulucrypt and i must say it's well done it has many features

cheers 
Stef

**Comment by mhogomchungu** [comment]
You are not the first person to make this suggestion and i will look into it.

Thanks.
