### ISSUE TITLE
Load zuluCrypt into system tray at startup

### ISSUE THREAD

**Issue by guttermonk** [mhogomchungu/zuluCrypt#175]
Would it be possible to add an option to load zuluCrypt at startup, and have it be minimized in the system tray? Keepass has a feature like that built into the program's settings, and I find it very helpful.

I tried adding zuluCrypt to my Startup Application in Ubuntu with a --minimize but zuluCrypt doesn't appear to have that switch. Also, just adding it to my Startup Applications caused the tray icon to not load. Not sure if it's possible, since it prompts me for my root password when the program starts, but this would be a nice feature.

Thank you!

**Comment by mhogomchungu** [comment]
The options is ```-e``` so the command to add is ```zuluCrypt-gui -e```

**Comment by guttermonk** [comment]
When I add that command to my Startup Applications, it causes the process to launch in the background but it doesn't show in the tray. This is odd because when I run the same command from terminal, after I've booted, it behaves as expected.

**Comment by mhogomchungu** [comment]
I do not know how to solve this, if you look at the code here[1], you will see that zuluCrypt first asks if the system is available and it shows the tray icon if it is, if it is not available, it then re asks the question 5 times on one second intervals if the system tray is available or not before giving up.

I suspect what is happening here is that at login, zuluCrypt is getting told that the system tray is available when it is not yet and zuluCrypt ends up showing the icon prematurely.

[1] https://github.com/mhogomchungu/zuluCrypt/blob/4edd9bf363ddef44dd4013bc52e6ff2c71de2399/zuluCrypt-gui/utility.cpp#L2024

**Comment by guttermonk** [comment]
I was able to use a python script from this Stack answer from fermmm to load the program into the tray at startup: https://askubuntu.com/a/1133211

I added this command to a startup script:
python3 ~/Programs/startup_closed.py -hide -c /usr/bin/zuluCrypt-gui

And then added the startup script to my Startup Applications.

Would it be possible to copy the "load at startup" option from KeepassXC and add it to the Zulucrypt options menu? Not sure how KeepassXC goes about loading on startup, but it might be worth a look. Regardless, having a check box in the options menu for that would make it more noob friendly. Love the program BTW.

**Comment by mhogomchungu** [comment]
Thank you and i will look into how KeepassXC does it.

**Comment by mhogomchungu** [comment]
I forgot to ask, what desktop environment are you using?

if GNOME, what extension are you using to show the tray icon.

**Comment by mhogomchungu** [comment]
My new code now looks like below and it closely resembes the keepassxc and it does  the following:-

1. It shows the icon and then goes to sleep for 2 seconds.
2. it wakes up and check if the icon is visible or not and if it is not then it shows it and goes back to sleep for 2 seconds again.
3. The above process repeats upto 5 times.

Keepassxc does it 5 times on 5 seconds intervals and zuluCrypt does it 5 times on 2 seconds intervals.
https://github.com/mhogomchungu/zuluCrypt/blob/48e982e5103acdc5da06632ea0ba4b3df11d4b42/zuluCrypt-gui/utility.cpp#L2018-L2045

**Comment by mhogomchungu** [comment]
Marking this one as closed but feel free to comment if the issue is still present.

**Comment by guttermonk** [comment]
Thank you!
