### ISSUE TITLE
What are the defaults?

### ISSUE THREAD

**Issue by mercertom** [mhogomchungu/zuluCrypt#179]
Using VeraCrypt on Windows, and it tries several different PRF and also TrueCrypt mode, but it won't unlock the volume. Can you describe the default volumes that zulucrypt would make, and possibly recommend an alternative to VeraCrypt or what settings I need to use to access volumes from Windows?

**Comment by mhogomchungu** [comment]
It should just work.

1. You created the volume with zuluCypt? If yes, what version.

2. How long is your password.

3. Is it made up of printable characters only?

**Comment by mercertom** [comment]
1. Probably the current version of 1-2 years ago.
2. about 10 characters
3. Yes.

I've managed to unlock the volume in LibreCrypt, I can browse and see all the files, correct names, etc. BUT, it hangs and can't be force quit if I try to interact with any of the files, like open or copy the files with any app.

**Comment by mhogomchungu** [comment]
Does your password use non latin characters?

**Comment by mercertom** [comment]
No, it's all very normal latin/utf/iso/english characters.

**Comment by mercertom** [comment]
Can you please describe the defaults?

**Comment by mhogomchungu** [comment]
Unlock the volume using zuluCrypt and then right click the entry on the UI and then select "properties" and post a screenshot of the generated window.

Crypto properties that were used when the volume was created should be on the properties window.

Defaults are used ONLY when creating a volume.

When unlocking a volume, ALL options are tried until a match is found so there is not point in asking for defaults when unlocking a volume.

I find it strange that zuluCrypt and LibreCrypt can unlock your volume but not VeraCrypt.

If you look at zuluCrypt code here[1], you will see that it first tries to unlock the volume normally and when that fails, it tries to unlock the volume using a back up header.

In VeraCrypt, you have to explicitly say you want the hidden header to be used and the option is seen in below screenshot. Try again in VeraCrypt with the backup header option set and try again.

[1] https://github.com/mhogomchungu/zuluCrypt/blob/8aebc7b630d8d527d0ede3413d4e8a5d71a10d54/zuluCrypt-cli/lib/open_tcrypt.c#L239-L248

![Screenshot_20220808_095744](https://user-images.githubusercontent.com/3496115/183358489-b24fda0a-521a-420b-bf0e-57579b2ba8bf.png)

**Comment by mercertom** [comment]
Tried backup header option, still fails. Librecrypt doesn't really work, it's read-only and buggy, but it does unlock the volume and I see all the files inside. I don't have access to zulucrypt in windows.

**Comment by mhogomchungu** [comment]
>If your volume a TrueCrypt volume or a VeraCrypt volume?

> Unlock the volume using zuluCrypt and then right click the entry on the UI and then select "properties" and post a screenshot of the generated window.

You did not respond to the above part. I need to know more about your volume.

**Comment by mercertom** [comment]
I dont have zulucrypt in windows. Whats the default? thats what the volumes are, and why Im asking.

-------- Original Message --------

**Comment by mhogomchungu** [comment]
This LibreCrypt [FAQ](https://github.com/t-d-k/LibreCrypt/blob/master/docs/FAQ.md#tc) says it can not open TrueCrypt volumes. They didnt mention it but i suspect it also does not support VeraCrypt volumes.

zuluCrypt defaults to LUKS volumes when creating a volume and LibreCrypt supports it as its primary volume type.

I suspect the reason why VeraCrypt can not open your volume is because it is neither a TrueCrypt volume nor a VeraCrypt volume. VeraCrypt supports only these two formats.

I suspect the reason why zuluCrypt can open it and LibreCrypt can open it also is because your volume is a LUKS volume.

zuluCrypt supports LUKS1, LUKS2, PLAIN-dmcrypt, VeraCrypt and TrueCrypt volumes.

Summary, you cant use your volume with VeraCrypt application.

**Comment by mhogomchungu** [comment]
Closing this one as "invalid"

**Comment by mercertom** [comment]
"zuluCrypt defaults to LUKS"

is part of the answer to "What are the defaults?"
