### ISSUE TITLE
installed 6.1.0, but "About" still show as 6.0.0

### ISSUE THREAD

**Issue by thisisgregm** [mhogomchungu/zuluCrypt#183]
Hi,
Just installed 6.1.0 for Ubuntu Jammy 22.04, but "About"still show as:
Version : 6.0.0
Copyright: 2011-2021...

should be 6.1.0
and 2011-2022 I guess.

also from terminal:
zuluMount-cli --version
and
zuluCrypt-cli --version

return both the same:

Version  : 6.0.0
Copyright: 2011-2021 Francis Banyikwa,mhogomchungu@gmail.com
License  : GPLv2+

Synaptic shows the correct version.

**Comment by mhogomchungu** [comment]
Thanks for the report, the commit logs are here[1] and those packages were build with a commit from "May 20, 2022" instead of the last commit from "May 21, 2022".

Will rebuild them with correct info within day or two.

[1] https://github.com/mhogomchungu/zuluCrypt/commits/master

**Comment by mhogomchungu** [comment]
New version is out and it has a fix for this issue

https://github.com/mhogomchungu/zuluCrypt/releases/tag/6.2.0
