### ISSUE TITLE
Accessing content in an unmounted volume

### ISSUE THREAD

**Issue by reymalahay** [mhogomchungu/zuluCrypt#184]
Hi there,

I am looking at this [post](https://superuser.com/questions/1261014/how-can-i-open-a-veracrypt-volume-without-mounting-it-ubuntu-16-04) that a maintainer responded to over four years ago.

i am trying to run the command sequence listed in that post:
```
zuluCrypt-cli -O /dev/sdxx -e rw -t vcrypt
```
 obviously i modified the command sequence to suit my situation, but i keep getting this error:

```
ERROR: Required option( device path ) is missing for this operation
```

Please advise.

Thanks in advance,
rey malahay

**Comment by mhogomchungu** [comment]
You are missing the "-d" option, the command to use should be 

```
zuluCrypt-cli -O -d /dev/sdxx -e rw -t vcrypt
```

**Comment by reymalahay** [comment]
Hi there,

thank you. that worked; the article's version of that command sequence was missing the '-d' option.

before i close this, will you be building in repair tools? i am looking for something to repair corrupt superblocks.

Thanks in advance and kind regards,
rey malahay
