### ISSUE TITLE
debian build instructions need updating for new version

### ISSUE THREAD

**Issue by learntofly83** [mhogomchungu/zuluCrypt#19]
https://github.com/mhogomchungu/zuluCrypt/blob/master/debian_package_info/BUILD_INSTRUCTIONS

line 37 AS IS: tar cf - . | xz -zf - > ../zulucrypt_4.7.6.orig.tar.xz
line 37 TO BE: tar cf - . | xz -zf - > ../zulucrypt_4.7.7.orig.tar.xz

line 93 AS IS: tar cf - . | xz -zf - > ../zulucrypt_4.7.6.orig.tar.xz
line 93 TO BE: tar cf - . | xz -zf - > ../zulucrypt_4.7.7.orig.tar.xz

build fails without

**Comment by mhogomchungu** [comment]
Just fixed the errors you pointed out[1]

shukran.

[1] https://github.com/mhogomchungu/zuluCrypt/commit/dc61cafdcb158040a199ec68cc6d90c96dc128ef

**Comment by learntofly83** [comment]
this too:

https://github.com/mhogomchungu/zuluCrypt/blob/master/rpm/BUILD_INSTRUCTIONS

**Comment by mhogomchungu** [comment]
done.

Simple fixes like these are some of the most easiest way to start in FOSS projects.

If you had submitted these changes as a pull request,you would have learned the following if you dont know them already.

1. How to fork a project in github.
2. How to compare changes in your tree against my tree after you have made your changes.
3. How to issue pull requests.

**Comment by learntofly83** [comment]
Thanks for the advice.

I'm a novice, I don't understand the concepts you speak of but I will research. Thanks for the package.

Regards
