### ISSUE TITLE
Remove public domain from the copyright file

### ISSUE THREAD

**Issue by imciner2** [mhogomchungu/zuluCrypt#190]
In 2016 the `zuluCrypt-gui/md5` folder was removed, removing all public domain code. However the license file still lists it as a license used in the project https://github.com/mhogomchungu/zuluCrypt/blob/d1509759b8dc6e74d3700a5899fccf5c679df4a7/copyright#L33. It would be good to cleanup the license file by removing that.

**Comment by imciner2** [comment]
It is also present in the included Debian copyright file: https://github.com/mhogomchungu/zuluCrypt/blob/d1509759b8dc6e74d3700a5899fccf5c679df4a7/debian.upstream/copyright#L13

**Comment by mhogomchungu** [comment]
Done

https://github.com/mhogomchungu/zuluCrypt/commit/0570f59bbf1097ede28cf4e117f95e9d103d440c

**Comment by imciner2** [comment]
Thanks!
