### ISSUE TITLE
Could you add the ability to set mount options?

### ISSUE THREAD

**Issue by Gooberslot** [mhogomchungu/zuluCrypt#20]
I know if you use the zuluMount-cli -Y option you can set mount options but could you add that ability to the gui? If it can remember those options if you save a volume as a favorite that would be good also. The main reason I need this is to mount FAT32 volumes with the utf8 option so I can get unicode filenames.

**Comment by mhogomchungu** [comment]
what version of zuluCrypt are you using?

Its possible to set mount options in zuluMount-gui.

Steps to do so:
1. click to mount your volume.
2. at the prompt to set mount name,click "option" button followed by selecting "set file system options" and enter "utf8" in the generated prompt.

If you want this particular file system to always be mounted with "utf8" option,then create a zuluCrypt config file at: ```"/etc/zuluCrypt/fs_options"``` and then add something like ``` UUID="368D-0BFB"   utf8``` where "368D-0BFB" if the UUID value of the fat32 file system.

You can get UUID values of file systems by using "blkid" tool.

if you want all fat32 file systems to be mounted with "utf8" option,then create a zuluCrypt config file at ```/etc/zuluCrypt/generic_fs_options``` and then add ```vfat utf8```

**Comment by Gooberslot** [comment]
Ah, I was using the zuluCrypt-gui instead of the zuluMount-gui. Nice to know about the fs_options though.

**Comment by mhogomchungu** [comment]
Can you confirm that the ability to set mount options exists so that i can close this bug report.

**Comment by Gooberslot** [comment]
Sorry, I just tried it using the git version installed from the AUR (https://aur4.archlinux.org/packages/zulucrypt-git/) and when I clicked the "Set File System Options" option nothing happened. No dialog box or anything.

**Comment by mhogomchungu** [comment]
can you update from git and try again?,there was a typo that was causing the problem and i just fixed it here: https://github.com/mhogomchungu/zuluCrypt/commit/54d078ec8e263092c64d43a3dcc96ba768c3eff4

**Comment by Gooberslot** [comment]
Seems to be working now.
