### ISSUE TITLE
I am able to create a Challenge-Response protected volume, but unable to open it 

### ISSUE THREAD

**Issue by piekay** [mhogomchungu/zuluCrypt#203]
### Output of zulucrypt-cli

> Version  : 6.2.0
Copyright: 2011-2022 Francis Banyikwa,mhogomchungu@gmail.com
License  : GPLv2+

### Operating System

> Void Linux

### Steps to reproduce

> Use zuluCrypt to create a challenge-response protected VeraCrypt volume, then try to unlock it

### Terminal Output

> Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Enter passphrase: ERROR: Could not get passphrase in silent mode
--

**Comment by jonathancross** [comment]
Maybe there is something here that will help debug: https://github.com/mhogomchungu/zuluCrypt/issues/118#issuecomment-497945622
