### ISSUE TITLE
Choose Full Path of Mount Point with zuluMount

### ISSUE THREAD

**Issue by angelic-sedition** [mhogomchungu/zuluCrypt#21]
Unless I am misunderstanding, currently one can only mount a volume under `/run/media/private/$USER/` using the -z flag with zuluMount-cli. I normally mount my encrypted volumes under ~/ and think it would be nice if there was also an option to choose the full path of the mount point.

**Comment by mhogomchungu** [comment]
The mount point path is made up of two components,```/run/media/private/$USER/``` is the prefix part and is set at compile time,the postfix part is set at run time and is the part that is controlled by "-z" option.

The full mount point path may look like ```run/media/private/$USER/blablaba```

If you the prefix part to be ```~/```,then recompile the project with ```-DHOMEMOUNTPREFIX=true``` option. All compile time options are listed in the build instructions page[1]

[1] https://github.com/mhogomchungu/zuluCrypt/blob/master/BUILD_INSTRUCTIONS

**Comment by mhogomchungu** [comment]
I am closing this one since its already possible to have  mount points in "~/".

The reason why the prefix part of the mount point is set at compile time and users are not allowed to change it is because it is used to keep track of what user mounted what volume and it has to be predictable and unique to each user.

**Comment by angelic-sedition** [comment]
Would you consider adding an option to change the prefix to $HOME (and no other prefix)? Is there some reason why it would be undesirable for a user to have volumes mounted under both /run... and $HOME?

**Comment by mhogomchungu** [comment]
There is already an option to change the mount prefix to "$HOME" and the option is set by compiling the application with "-DHOMEMOUNTPREFIX=true" option.I already said this so i dont get what you are asking.

Do you want zuluCrypt to have an option to allow a user to sometimes use "$HOME" and other times to use "/run/media/private/$USER"? If yes,then why would want some mount point to be in "$HOME" and other mount points to be in "/run/media/private/$USER"? it is possible to do so but it will add more code paths and i dont see the usecase for it.

**Comment by angelic-sedition** [comment]
I meant a runtime option.

Well one use case might be to have local volumes mounted under $HOME and external volumes mounted under /run/media/private/$USER, but you're right. I don't see that much of a use case for it. I'd like to use zuluMount-cli in my scripts and don't like the idea of it behaving differently depending on how it is compiled, but if you think it best to leave this option set at compile time, then that is fine.

**Comment by mhogomchungu** [comment]
I just looked at the code and there is a runtime option as its possible to override[1] the compile time option that creates mount prefix at "/run/media/private/$USER" by passing "mount-prefix=home" as a mount option with "-e" but it requires a user being a member of group "zulumount".

Will you be ok with this requirement?

example of how to override at runtime the default mount prefix to use to home mount prefix.

```
[mtz@ink ~]$ zuluMount-cli -m -d /dev/sdc1 -p xxxx -e mount-prefix=home
SUCCESS: plain volume opened successfully
volume mounted at: /home/mtz/xxx
```

[1] https://github.com/mhogomchungu/zuluCrypt/blob/7f4fd2aeaf390c9d56bb06bc8be5fea2f3da0e8f/zuluCrypt-cli/bin/create_mount_point.c#L274

**Comment by angelic-sedition** [comment]
This works fine. Thank you for letting me know. However, I notice that zuluMount will not mount a volume if the mount point path already exists even if it is empty. This behaviour isn't as noticeable for the default mount prefix, since the mount path created under "/run/media" doesn't persist across reboots, but it's especially noticeable with the mount path under /home since zuluMount-cli will fail with the same mount command after unmounting (unless the created mount path is deleted every time). I think it would make sense to not give an error if the specified mount path is an empty directory.

**Comment by mhogomchungu** [comment]
The mount point path is "owned" by zuluCrypt and that is why it complains if the path is found to be occupied.Having a view that zuluCrypt owns the mount point makes decisions easy as it can just unconditionally delete the mount point when unmounting succeeds.

Allowing usage of mount path if they are found to already exist will complicate things as questions about whether the mount point should be deleted or not after unmounting will come up and trying to answer them will lead to a switch and that is something i do not want to do as the switch will also have to be present in the GUI and it will complicate the GUI.

**Comment by angelic-sedition** [comment]
I'm not used to having this behaviour for local volumes (I'm used to having to manually create the mount point), but for zuluMount, it does make a lot more sense to create and delete the mount point itself. Thank you for explaining it to me and for the help.

**Comment by mhogomchungu** [comment]
Are you still interested in having the mount point not getting deleted on unmount and being reused on mounting?

I should be able support it but with a compile time switch.

**Comment by noctuid** [comment]
I'm fine with the mount point getting deleted. It's not much of an issue (just a minor difference from how other programs like truecrypt behave). I don't think I would bother using the compile time switch personally.

**Comment by noctuid** [comment]
Thank you. I'll keep it in mind.
