### ISSUE TITLE
encrypted file date/time modification on usage / unmount

### ISSUE THREAD

**Issue by BluesBiker** [mhogomchungu/zuluCrypt#212]
One great feature of the original Truecrypt program was that the encrypted file date/time was never modified.
At least, the file creation and modification time was 'touched' to its original value at any file modification, so that it was not possible to say you worked on it.

As a privacy concern, it is much easier to identify which is your encrypted file if it one of the latest you opened.

It is a simple but very important update to the program behavior.

**Comment by mhogomchungu** [comment]
Cllosing for lack of activity.
