### ISSUE TITLE
Failed To Locate Or Run Yubikey's "ykchalresp" Program.

### ISSUE THREAD

**Issue by JackDinn** [mhogomchungu/zuluCrypt#214]
System:
Host: greg-venusseries Kernel: 6.9.10-1-MANJARO arch: x86_64 bits: 64
Desktop: KDE Plasma v: 6.0.5 Distro: Manjaro Linux
Machine:
Type: Desktop System: Micro (HK) Tech product: Venus Series v: N/A
serial:
Mobo: Shenzhen Meigao Equipment model: AHWSA serial:
UEFI: American Megatrends LLC. v: AHWSA.1.22 date: 03/12/2024

```
❱ykchalresp -V
1.20.0
❱which ykchalresp
/usr/bin/ykchalresp
```
```
***************************
/usr/bin/zuluCrypt-cli -S
***************************
***************************
/usr/bin/zuluCrypt-cli -S
***************************
***************************
/usr/bin/ykchalresp -2 -i -
***************************
```
```
Aug 01 17:58:07 greg-venusseries zuluCrypt-gui[263494]: Failed to get a responce from ykchalresp
Aug 01 17:58:07 greg-venusseries zuluCrypt-gui[263494]: StdOUt:
Aug 01 17:58:07 greg-venusseries zuluCrypt-gui[263494]: StdError:Yubikey core error: timeout
```
```
❱zuluCrypt-cli -v
Version  : 6.2.0
Copyright: 2011-2022 Francis Banyikwa,mhogomchungu@gmail.com
License  : GPLv2+

⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼ /home/greg ⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼
❱zuluCrypt-gui -v

Version  : 6.2.0
```
Iv only just got my Yubikeys so im just trying things out, sorry if iv just missed something obvious although i have searched.

**Comment by JackDinn** [comment]
Ok i have managed to get it to successfully create a volume file to test this with. It said it was successful. But when i try to mount/access the encrypted file i get the error 

"Enter passphrase: ERROR: Could not get passphrase in silent mode"

**Comment by mhogomchungu** [comment]
You have to press your Yubikey when zuluCrypt is waiting for its password to tell it to release its password.

I would advice to run your Yubikey from the terminal to know how it works before using it through another tool. If you are not careful, you may end up creating a volume with an empty password.

**Comment by JackDinn** [comment]
Iv tried pressing the key in every way shape and form. Tried pressing it before, during and after.
I dont care about the volume atm as im just testing and they are disposable until i can at least get it to work but i have not been able to.

**Comment by JackDinn** [comment]
I seems that i am not the only one seeing this same problem when testing?

It would have been really neat to have been able to use the yubikey in the way the zulu GUI seems to imply that it should be :disappointed: 

https://forum.manjaro.org/t/zulucrypt-yubikey/166367

Thank you for the development of zulucrypt though, its great even without being able to use my new yubikey.

**Comment by mhogomchungu** [comment]
1. Run ```ykchalresp``` command from the terminal with options that causes it to give its password.
2. Tell me the command you use and i will help you in setting up zuluCrypt to use it. zuluCrypt uses default options of ```-2 -i -``` because those are what works with my yubikey and the password is given only after pressing the button on the key. I do not know how your yubikey works and you are not being helpful.

**Comment by JackDinn** [comment]
i can send it "test" as a test challenge.
```
❱ykchalresp -2 "test"
47abbca32cc781c97a773608ae5551a1cdc390c5
```
but i dont know what challenge would be sent to it from zulu .

Does my Yubikey not work the same way as everyone else's?

This is my Yubico Authenticator setup for slot 2 challenge/response

![Screenshot_20240801_201706](https://github.com/user-attachments/assets/6c0a4814-b9e1-446e-b8d0-e0c9d8987f7e)


I dont know how to show any more detail about the slot 2 but its set to 

Challenge-response
Program a challenge-response
credential

❱ykman otp info
Slot 1: programmed
Slot 2: programmed

**Comment by mhogomchungu** [comment]
0. Close zuluCrypt.
1. Go to zuluCrypt config file located at ```$HOME/.config/zuluCrypt/```
2. Open the config file with a text editor and look for option named ```YkchalrespArguments```.
3. Change its value to ```-2```.
4. Save the text file and close it.
5. Start zuluCrypt.
6. Create a volume using key ```47abbca32cc781c97a773608ae5551a1cdc390c5```.
7. Open the volume you just created with zuluCrypt using your yubikey with a password of "test".

**Comment by JackDinn** [comment]
```
❱cat ~/.config/zuluCrypt/zuluCrypt.conf
[General]
AutoMountPassWordBackEnd=none
AutoOpenFolderOnMount=true
ClearPassword=true
ConfigLocation=/home/greg/.config/zuluCrypt/
DefaultUnlockingVolumeType=0
Dimensions=749, 221, 1677, 979, 298, 336, 95
FileManager=xdg-open
IconName=zuluCrypt
LocalizationLanguage=en_US
PlainDmCryptOptions=aes.cbc-essiv:sha256.256.sha256, aes.cbc-essiv:sha256.256.sha512, aes.cbc-essiv:sha256.256.sha1, aes.cbc-essiv:sha256.256.ripemd160, aes.cbc-essiv:sha256.512.sha256, aes.cbc-essiv:sha256.512.sha512, aes.cbc-essiv:sha256.512.sha1, aes.cbc-essiv:sha256.512.ripemd160, aes.xts-plain64.256.sha256, aes.xts-plain64.256.sha512, aes.xts-plain64.256.sha1, aes.xts-plain64.256.ripemd160, aes.xts-plain64.512.sha256, aes.xts-plain64.512.sha512, aes.xts-plain64.512.sha1, aes.xts-plain64.512.ripemd160
ReadOnly=false
RemoveYkchalrespNewLineCharacter=true
ScaleFactor=1
ShowOnlyOccupiedSlots=true
ShowTrayIcon=true
SupportedFileSystems=ext4, vfat, ntfs, ext2, ext3, exfat, ntfs, btrfs
UseDmCryptForRandomData=false
YkchalrespArguments=-2
doNotMinimizeToTray=false
mountWithSharedMountPoint=false
unMountVolumesOnLogout=false
```

created a new file volume with the setting "Key" and added 
47abbca32cc781c97a773608ae5551a1cdc390c5
47abbca32cc781c97a773608ae5551a1cdc390c5

to both password fields, i hope that is what you meant.

It said created ok.

I go to open the created file, change the setting to "Yubikey..." and put "test" into the password field.
![Screenshot_20240803_183123](https://github.com/user-attachments/assets/374b2455-d406-4983-ac4d-718ebd215927)

I still get the same response without any delay.

![Screenshot_20240803_183153](https://github.com/user-attachments/assets/b02f58d0-b7c4-4711-819c-f0f4854b8c4b)

**Comment by JackDinn** [comment]
Iv just found that this works in the shell, but not in the GUI.
```
❱/usr/bin/zuluCrypt-cli -o -d "/home/greg/testdir/ccc" -m "zulu" -e rw  "" -p (ykchalresp -2 "test")
SUCCESS: luks volume opened successfully
volume mounted at: /run/media/private/greg/zulu
```

**Comment by mhogomchungu** [comment]
Sorry for a later reply.

There was a bug and is it is now fixed, can you build the project from source and test?

**Comment by JackDinn** [comment]
I will give it a go later today and let you know.

Thx for looking into it, appreciated.

**Comment by mhogomchungu** [comment]
I will make a new release tomorrow.

AUR is usually updated within a day or two.

**Comment by mhogomchungu** [comment]
Hi, i will make a new release of monday, just discovered something i need to investigate it first.

**Comment by mhogomchungu** [comment]
New version is out: https://github.com/mhogomchungu/zuluCrypt/releases/tag/7.0.0

**Comment by JackDinn** [comment]
Nice. Thank you. Will check on the AUR in a couple of days.
