### ISSUE TITLE
Unable to open hidden volume with password, key file, and PIM value combination

### ISSUE THREAD

**Issue by RyanPlant** [mhogomchungu/zuluCrypt#216]
[This issue is addressed in https://github.com/mhogomchungu/zuluCrypt/commit/1d5abba06293d628716e23559b1ea567432ce1c9 and will be part of the 7.0 release]

**Issue**: 
ZuluCrypt fails to unlock a hidden volume created by VeraCrypt with a password, one or more key files, and PIM value.

**Inputs**:
Volume Type: VeraCrypt
PIM Value: XXXX
TrueCrypt/VeraCrypt Keys (dialog screen opens to select key files)
'Enter A Passphrase Below To Be Used To Open The Volume' : [password]

**Context**:
I have verified the keyfiles, PIM value, and password work using VeraCrypt.
Keyfiles are text-based (generated by the VeraCrypt application) and are ~400kb each.

**Comment by mhogomchungu** [comment]
Version 7.0.0 is already [released](https://github.com/mhogomchungu/zuluCrypt/releases/tag/7.0.0).

Can you test with this version?

**Comment by DockSavior** [comment]
I checked on version 7.1.0, I also failed to open the veracrypt volume with pim, keyfile and password

**Comment by mhogomchungu** [comment]
Does your password contain at least one character that is not ASCII?

**Comment by DockSavior** [comment]
> Does your password contain at least one character that is not ASCII?

No. All characters included in the set are included in the ASCII set:
PASS!}WORD

**Comment by DockSavior** [comment]
the problem is urgent
