### ISSUE TITLE
Could not get passphrase in silent mode

### ISSUE THREAD

**Issue by Wordsmouth** [mhogomchungu/zuluCrypt#217]
Trying to unlock a container I just created as a test with zuluCrypt using a password and ykchallenge ends with the message
"Could not get passphrase in silent mode"
I already tried to change the config regarding the last character like mentioned in other issues but I could not solve the "Could not get passphrase in silent mode" message.

**Comment by mhogomchungu** [comment]
This is fixed here: https://github.com/mhogomchungu/zuluCrypt/issues/214
