### ISSUE TITLE
ZuluCrypt  can't mount files if passphrase contains special characters

### ISSUE THREAD

**Issue by gc-user** [mhogomchungu/zuluCrypt#220]
After updating from v6.0.0 to v7.0.0, ZuluCrypt stopped being able to mount files if the passphrase contains special characters.
The error message reads `Volume could not be opened with the presented key.`

ZuluMount (both versions v6.0.0 and v7.0.0) on the other hand has no problem mounting those exact files. And neither has ZuluCrypt v6.0.0 when downgrading again.

I compiled v7.0.0 myself, but seeing other issues regarding problems with special characters it might not be a problem of compiling

**Comment by mhogomchungu** [comment]
I suspect the problem is [here](https://github.com/mhogomchungu/zuluCrypt/blob/f4cbe11663d2fdb413fe13924a6f57adf20464fa/zuluCrypt-gui/password_dialog.cpp#L673)

On that line, replace "toUtf8" with "toLatin1", recompile and see if it solves the problem.

**Comment by gc-user** [comment]
Thanks for the reply.
I just compiled using a patch to make the change. Now I get the following error message popup at start and when I enter the password when trying to open an encrypted vault file.
![zulucrypt error message 1](https://github.com/user-attachments/assets/5d70a8ad-a89b-4390-b5b8-54376d49094f)


There's a second popup when confirming the first one when trying to open an encrypted vault file.
![zulucrypt error message 2](https://github.com/user-attachments/assets/bce408ef-0a66-425c-80e8-f1275998eb1a)


Is that explainable by this change or some other issue?

The patch used:

--- a/zuluCrypt-gui/password_dialog.cpp
+++ b/zuluCrypt-gui/password_dialog.cpp
@@ -670,7 +670,7 @@
 {
 	this->disableAll() ;
 
-	m_key = key.toUtf8() ;
+	m_key = key.toLatin1() ;
 
 	m_device = utility::resolvePath( m_ui->OpenVolumePath->text() ) ;

**Comment by mhogomchungu** [comment]
What options did you pass to cmake when building.

I suspect you are running zuluCrypt-gui from a build folder without first installing it and the problem is caused by zuluCrypt-gui not finding its executables since it looks for them in installation folders that where set when building.

**Comment by gc-user** [comment]
Yeah, that is a separate issue. I forgot that the qt6 version needs different dependencies for building which I haven't yet figured out.

When compiling the qt5 version with the patch all is good now.

Sorry about that and thank you for the fix!
