### ISSUE TITLE
 zulucrypt failed to connect to zulupolkit

### ISSUE THREAD

**Issue by ivtb** [mhogomchungu/zuluCrypt#223]
Hi,
I get the error, at the start: " zulucrypt failed to connect to zulupolkit".
I run zulucrypt on Fedora 41, and the zc version is 7.0.0.
I have updated my OS by "dnf --upgrade", today, and after that, I get the error.
I installed zulucrypt using "dnf install zulucrypt".
I don't find information about what zulupolkit is :-(
Anyone sees this error?

**Comment by mhogomchungu** [comment]
1. zuluCrypt-gui is a GUI and it runs from a normal user account.
2. zuluCrypt-cli is a CLI and it runs from root's account.
3. zuluPolkit is a CLI and it runs from root's account. 
4. zuluPolkit is started by zuluCrypt-gui and it gains root's privileges through polkit after it is given permission by the user.
5. When unlocking a volume, zuluCrypt-gui sends zuluCrypt-cli command to zuluPolkit and zuluPolkit executes the command.
6. All 3 mentioned tools should be installed together and be where zuluCrypt-gui expects them to be.

**Comment by ivtb** [comment]
Thank you for the explanation, very clear!
Anyway, I think the problem is not directly related to zulucrypt, because it stopped working after a "dnf upgrade" command on my fedora 41.
The same zc release (7.0.0.) keeps on working on an EndeavourOS installation.

**Comment by ivtb** [comment]
Additional information: Today I have updated my fedora 41.  Polkit has been updated, now this is what I have installed: **polkit-kde-0:6.2.4-1.fc41.x86_64**.
I use KDE.
Unfortunately, nothing has changed, I still get the same error :-(

**Comment by mhogomchungu** [comment]
I am also getting this error when using zuluCrypt with Qt6.

Is zuluCrypt using Qt5 or Qt6 in Fedora?

**Comment by cuervo011** [comment]
ldd seems to indicate Qt6.  /var/log/messages says:

Nov 28 17:07:59 fedora zuluCrypt-gui[7189]: QLocalSocket::connectToServer: Invalid name
Nov 28 17:08:00 fedora zuluCrypt-gui[7189]: ERROR: Failed To Connect To zuluPolkit

**Comment by mhogomchungu** [comment]
This is fixed now, the problem was with polkit.

**Comment by mhogomchungu** [comment]
New version is out and it has a fix for this issue

https://github.com/mhogomchungu/zuluCrypt/releases/tag/7.1.0

**Comment by ivtb** [comment]
Very good news! It is not yet in fedora repository, but I will check in some days.
Thank you for the info.

**Comment by ivtb** [comment]
Installed from fedora repository the new version. EXCELLENT! It works, no problems, very good. Thank you a lot, mhogomchungu. Great job!
