### ISSUE TITLE
Extract zuluCrypt and zuluMount icons for easy replacing them by external icon themes

### ISSUE THREAD

**Issue by FadeMind** [mhogomchungu/zuluCrypt#24]
Hi 
I looking for easy replacing default zulu* icon set for adjust them with main currently using icon theme.
Solution for now is replacing PNG files directly in sources directory before compiling:
ZuluCrypt icon tray after replaced them in SRC (48x48px):
![screenshot_20151205_090656](https://cloud.githubusercontent.com/assets/9846948/11606836/9d1538c2-9b2f-11e5-8eb1-181aed56d712.png)

IN SRC PNG icons are in:
zuluCrypt-4.8.0/zuluCrypt-gui/
zuluCrypt.png
and
zuluCrypt-4.8.0/zuluMount-gui/
zuluCrypt.png
zuluMount.png

Reference : https://github.com/varlesh/papirus-pack-kde/issues/50

For example: clementine player using custom icon themes without any issues (and it is qt app too).

**Comment by mhogomchungu** [comment]
Did you create these icons yourself?

If yes,are you offering them to the project so that they can be included?

I will look into adding an option to select icons sets.

**Comment by mhogomchungu** [comment]
what desktop environment are you using? it looks slick

**Comment by FadeMind** [comment]
@mhogomchungu 
Author of icons is @varlesh 

I helping improve https://github.com/varlesh/papirus-pack-kde

I just replaced in SRC these icons.
SRC:
![zulucrypt](https://cloud.githubusercontent.com/assets/9846948/11614650/61104022-9c49-11e5-93d8-5fba08a47d05.png)
![zulumount](https://cloud.githubusercontent.com/assets/9846948/11614651/61175524-9c49-11e5-8678-d271633277d1.png)
[zuluCrypt.svg.zip](https://github.com/mhogomchungu/zuluCrypt/files/53234/zuluCrypt.svg.zip)
[zulucrypt.zip](https://github.com/mhogomchungu/zuluCrypt/files/53235/zulucrypt.zip)

Plasma 5 KDE with Papirus theming.

**Comment by FadeMind** [comment]
@mhogomchungu  Papirus icons are licensed under Creative Commons Attribution-ShareAlike 4.0
https://github.com/varlesh/papirus-pack-kde/tree/master/icons/papirus

**Comment by mhogomchungu** [comment]
I just made a commit[1] that allows changing the two icons by replacing zuluCrypt.png and zuluMount.png files in "$INSTALL_PREFIX/share/pixmaps/" folder.The full path in your system will probably be "/usr/share/pixmaps".

Can you confirm that you can have any icon you want simply by replacing default icons to your preferred icons?

[1] https://github.com/mhogomchungu/zuluCrypt/commit/42a9647727c3321c91fa88e7f22a6661d0e38df4

**Comment by FadeMind** [comment]
@mhogomchungu  Good job. 
Simply replace in pixmaps directory PNG files.
Icon is get from main theme curretly used (see taskbar)
![screenshot_20151206_191657](https://cloud.githubusercontent.com/assets/9846948/11614817/2159d600-9c4e-11e5-93af-c0e6fc77d5a2.png)

**Comment by FadeMind** [comment]
I will test one more scenario... one sec..

**Comment by FadeMind** [comment]
@mhogomchungu  NOPE.It's as I suspected. App looking in pixmaps, but should follow icons  dir in `/usr/share/icons/hicolor/48x48/apps/`
or

For example: clementine just following:
/usr/share/icons/papirus/16x16/apps/

![screenshot_20151206_193640](https://cloud.githubusercontent.com/assets/9846948/11614887/b360af4a-9c50-11e5-8a0c-51b6e8deab20.png)

**Comment by mhogomchungu** [comment]
Just made another commit[1] and zuluCrypt now looks for icons at "$INSTALL_PREFIX//share/icons/hicolor/48x48/apps/"

[1] https://github.com/mhogomchungu/zuluCrypt/commit/6cb868261333593d5b4539d01331ea82854ae878

**Comment by FadeMind** [comment]
Second sample: 
KeepassX using custom tray apps icon from current used theme (if keepassx icon IS customized).
![screenshot_20151206_195111](https://cloud.githubusercontent.com/assets/9846948/11614941/b7661a42-9c52-11e5-8d4f-c06f9cfa9dd8.png)

See:
https://github.com/keepassx/keepassx/search?utf8=%E2%9C%93&q=QIcon
https://github.com/keepassx/keepassx/blob/master/share/CMakeLists.txt

Your new setup works 50/50:
App bar using custom icon from used theme (papirus). 
Tray icon using main installed png file from hicolor dir.

**Comment by FadeMind** [comment]
Second sample: copyq app using whole customized icon tray and App if it is available:
https://github.com/hluk/CopyQ/search?utf8=%E2%9C%93&q=QIcon
![screenshot_20151206_200327](https://cloud.githubusercontent.com/assets/9846948/11614998/74da58c6-9c54-11e5-904f-e9475c8463a9.png)

Reference: https://github.com/varlesh/papirus-pack-kde/commit/03299fa63c95bd2894ec616555e9c868f522c9d6

**Comment by mhogomchungu** [comment]
can you log out and then log in and check again if its still 50/50.

Its the same icon,it either work in both places or dont work in places.

**Comment by FadeMind** [comment]
@mhogomchungu 
It is like previous:
![screenshot_20151206_202128](https://cloud.githubusercontent.com/assets/9846948/11615096/43d4ac2e-9c57-11e5-9a07-f06161156eed.png)
In the past default zC zM icons were in both places (taskbar and tray).
Now Taskbar using Theme icon, Tray using build in icon (exactly like octopi BTW).
Simple solution for now is using black  icons from @varlesh theme or reconfigure whole QIcon class :smile:

**Comment by mhogomchungu** [comment]
Can you try now,i made another commit that uses QIcon::fromTheme() API[1]

[1] https://github.com/mhogomchungu/zuluCrypt/commit/00bdee0c36f42f821a5d887747b98e9143ee32c1

**Comment by FadeMind** [comment]
Now is GOOD:
![screenshot_20151206_204226](https://cloud.githubusercontent.com/assets/9846948/11615167/e1af1e14-9c59-11e5-9473-981e3457f49c.png)

Thanks for this ;)

**Comment by FadeMind** [comment]
After install 16x16 zulu icons in black:
![screenshot_20151206_204801](https://cloud.githubusercontent.com/assets/9846948/11615197/ac106154-9c5a-11e5-9800-d4398190bad7.png)

**Comment by mhogomchungu** [comment]
Though i should update this bug report to mention that i just added code that allows changing zuluCrypt-gui and zuluMount-gui icons at run time by selecting a different icon entry at "menu-options->select icons" in zuluCrypt-gui and "menu->select icons" in zuluMount-gui.

Icons are search from "$install_path/share/icons/hicolor/48x48/apps" and zuluCrypt icons must start with "zuluCrypt" name and zuluMount icons must start with "zuluMount" name.

All icons must have a .png extension.

An example of a full path of a zuluCrypt icon is "/usr/share/icons/hicolor/48x48/apps/zuluCrypt-papirus.png"

**Comment by FadeMind** [comment]
@mhogomchungu fcons are made by @varlesh. I am just `active member` of papirus-suite project.
Thanks for this option.
