### ISSUE TITLE
Compile error in 4.9.0 version

### ISSUE THREAD

**Issue by terxw** [mhogomchungu/zuluCrypt#33]
Hi, i am trying to compile zulucrypt with these options:
  `cmake -DCMAKE_INSTALL_PREFIX=/usr -DSHARE_MOUNT_PREFIX=default -DUDEVSUPPORT=true -DNOGUI=false -DQT5=false -DHOMEMOUNTPREFIX=true -DREUSEMOUNTPOINT=true -DNOGNOME=false -DNOKDE=false -DCMAKE_BUILD_TYPE=RELEASE . ..
` 

 and i get make error:

`
Determining if the Q_WS_MAC exist failed with the following output:
Change Dir: /home/kangus/zuluCrypt-master/build/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/make "cmTryCompileExec2593207817/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec2593207817.dir/build.make CMakeFiles/cmTryCompileExec2593207817.dir/build
make[1]: Entering directory `/home/kangus/zuluCrypt-master/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/kangus/zuluCrypt-master/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building CXX object CMakeFiles/cmTryCompileExec2593207817.dir/CheckSymbolExists.cxx.o
/usr/bin/c++    -I/usr/include/qt4    -o CMakeFiles/cmTryCompileExec2593207817.dir/CheckSymbolExists.cxx.o -c /home/kangus/zuluCrypt-master/build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx
/home/kangus/zuluCrypt-master/build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx: In function ‘int main(int, char**)’:
/home/kangus/zuluCrypt-master/build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:8:19: error: ‘Q_WS_MAC’ was not declared in this scope
   return ((int*)(&Q_WS_MAC))[argc];
                   ^
make[1]: *** [CMakeFiles/cmTryCompileExec2593207817.dir/CheckSymbolExists.cxx.o] Chyba 1
make[1]: Leaving directory `/home/kangus/zuluCrypt-master/build/CMakeFiles/CMakeTmp'
make: *** [cmTryCompileExec2593207817/fast] Chyba 2

File /home/kangus/zuluCrypt-master/build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:
/* */
#include <QtCore/qglobal.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef Q_WS_MAC
  return ((int*)(&Q_WS_MAC))[argc];
#else
  (void)argc;
  return 0;
#endif
}

`

According to google, this is platform check and fail is expected, and cmake should continue.
All dependencies installed.

**Comment by mhogomchungu** [comment]
Are you trying to compile it on a mac?

zuluCrypt is currently linux only.

**Comment by mhogomchungu** [comment]
I am closing this one with an "invalid" tag since i think you are trying to build on a mac while zuluCrypt is currently linux only.

If you are building on linux then post the output of the cmake command and mention the linux distribution you are using.
