### ISSUE TITLE
Add "open" button in "open - hosted hard drive"

### ISSUE THREAD

**Issue by m1ga** [mhogomchungu/zuluCrypt#34]
It would be useful to add an "Open" button with the same function as double click in this menu:
![zulu](https://cloud.githubusercontent.com/assets/4334997/14941173/ba2cdaa0-0f92-11e6-9bf7-78bc1f678572.png)

So it will open the selected row. Since my uuid is Nil it won't do anything when I click the "Use UUID" button but it will open my drive when I double click the row (which you have to know)

**Comment by mhogomchungu** [comment]
done[1]

[1] https://github.com/mhogomchungu/zuluCrypt/commit/73b65f77ce865093d6d39297e6f416436e78fbeb

**Comment by m1ga** [comment]
That was quick! Awesome :+1:
