### ISSUE TITLE
truecrypt container cant be open

### ISSUE THREAD

**Issue by peekaa** [mhogomchungu/zuluCrypt#39]
I created crypted container in truecrypt 7.1a in wxp, and this can not open in debian testing/sid 4.9.0. zulucrypt. Its this one https://drive.google.com/open?id=0Bw77ydhNpM3VLTR2NktxRnJVVG8 - key is genius. Can you help pls?

![snimek z 2016-07-05 16-21-18](https://cloud.githubusercontent.com/assets/3026590/16587789/93174582-42cc-11e6-831c-142222aa0c91.png)

**Comment by mhogomchungu** [comment]
It opened fine here.

The volume uses vfat file system,does your system have support for this file system?

```
zuluMount-cli  zuluMount-gui  
[mtz@ink Downloads]$ zuluMount-cli -m -d tr1.tc -p genius
SUCCESS: tcrypt volume opened successfully
volume mounted at: /run/media/private/mtz/tr1.tc
[mtz@ink Downloads]$ zuluMount-cli -s -d tr1.tc
/dev/mapper/zuluCrypt-500-NAAN-tr1.tc-2444658016 active and is in use.
 type:          tcrypt
 cipher:        aes-xts-plain64
 keysize:       512 bits
 offset:        256 sectors / 128.0 KB
 device:        /dev/loop0
 loop:          /home/mtz/Downloads/tr1.tc
 mode:          read and write
 active slots:  Nil
 file system:   vfat
 total space:   19.7 MB
 used space:    0 B
 free space:    19.7 MB
 used%:         0%
 UUID:          "Nil"
 mount point1:  /run/media/private/mtz/tr1.tc
 mount point2:  Nil
[mtz@ink Downloads]$
```

**Comment by peekaa** [comment]
Well, not sure. Not sure how to find. mkfs.vfat in my system is. Thank you.

**Comment by peekaa** [comment]
My fault, I tried to mount as a user. From command line as a root it works. Would you be so kind - is it possible to use zuluCrypt as a normal user?  How to zulumount as a user?

**Comment by mhogomchungu** [comment]
Debian packages as distributed by debian requires zuluCrypt programs to run as with root's privileges.

Debian packages as distributed by me do not and you have two options:

1. Build zuluCrypt from source. Building a debian package yourself is easy and instructions to do so are here[2]. Dont hesitate to ask if you get stuck anywhere if you decide to take this route.

2. Use debian packages i distribute in zuluCrypt's front page[1]. Debian 8 packages should work.

[1] http://mhogomchungu.github.io/zuluCrypt/

[2] https://github.com/mhogomchungu/zuluCrypt/blob/master/debian_package_info/BUILD_INSTRUCTIONS

**Comment by mhogomchungu** [comment]
"mkfs.vfat" program is used to create a vfat file system,to check if you can mount a vfat file system,you were supposed to check if you have a vfat module in your system and you could have checked by running the following command as root.

```
locate vfat.ko | grep `uname -r`

```

You can tell if vfat module is loaded by running the following command as normal user.

```
lsmod | grep vfat

```

```lsmod``` gives a list of all loaded modules.

**Comment by peekaa** [comment]
```
:~$ locate vfat.ko | grep `uname -r`
/lib/modules/4.6.0-1-amd64/kernel/fs/fat/vfat.ko
:~$ lsmod | grep vfat
vfat                   20480  2
fat                    69632  1 vfat

```

Thank you.

**Comment by marciosouza20** [comment]
Hello Pekka, 

I'm debian maintainer the zulucrypt. What version of zulucrypt you are using? 
I'm using version 4.9.0-2, this is the version in Debian Sid/Testing.  In version 4.9.0-2 in my system working fine. 

![captura de tela de 2016-07-10 20-55-18](https://cloud.githubusercontent.com/assets/7623679/16716926/d187379c-46e0-11e6-9f48-5303fc94af85.png)

> My fault, I tried to mount as a user. From command line as a root it works. Would you be so kind - is  > it possible to use zuluCrypt as a normal user in gnome? How to zulumount-gui as a user?

When you run the zuluMount-gui via the menu icon, it runs the script zuluMount-gui-pkexec that calls zuluMount-gui. 

$ cat `which zuluMount-gui-pkexec`
#!/bin/sh
pkexec "/usr/bin/zuluMount-gui" -K `id --user` "$@"

The pkexec requests the password of an administrator user on Debian will usually be the root. That way zuluMount-gui/zuluCrypt-gui can perform administrative tasks. 

Regards.

**Comment by peekaa** [comment]
Hello,

thank you for reply.

:~$ apt show zulucrypt-gui
Package: zulucrypt-gui
Version: 4.9.0-2
Priority: optional
Section: utils
Source: zulucrypt
Maintainer: Marcio de Souza Oliveira <m.desouza20@gmail.com>
Installed-Size: 1 389 kB
Depends: libblkid1 (>= 2.16), libc6 (>= 2.14), libgcc1 (>= 1:3.0), 
libgcrypt20 (>= 1.7.0), libpwquality1 (>= 1.1.0), libqt5core5a (>= 
5.5.0), libqt5gui5 (>= 5.0.2), libqt5network5 (>= 5.0.2), libqt5widgets5 
(>= 5.0.2), libsecret-1-0 (>= 0.7), libstdc++6 (>= 4.5), 
libzulucryptpluginmanager1.0.0 (>= 4.9.0), zulucrypt-cli
Homepage: http://mhogomchungu.github.io/zuluCrypt
Tag: uitoolkit::qt
Download-Size: 377 kB
APT-Manual-Installed: yes
APT-Sources: http://httpredir.debian.org/debian stretch/main amd64 Packages

Not sure if you are talking about user or root if you write " in my 
system working fine". As a root it works here fine too, but its really 
big complication. I think there is no need to use root right to access 
tc files. Its like you can access as a user your usb flash drive, you 
can read, write, delete. TC files are much more like usb flash drives 
than anything else. Why not? Why would my wife and son take care about 
beeing root or not? Its trouble.

If you need to send any other logs, anything, pls do not hesitate tell me.

Thank you
Pavel




Dne 11.7.2016 v 02:22 marciosouza20 napsal(a):

**Comment by mhogomchungu** [comment]
``` I think there is no need to use root right to access tc files. Its like you can access as a user your usb flash drive, you can read, write, delete. ```

root's privileges are required and there is no way around it. The difference is that some solutions "hides" the requirement while others do not. My debian package or when building from source "hides" the requirement while official debian packages do not.

If you dont do these things as root user,then somebody else behind the scene is doing them as root user on your behalf.

It should also be possible to hide the requirement in the official debian package by changing project's polkit's config file i think.

**Comment by mhogomchungu** [comment]
I am closing this bug report since the question that opened the bug report is answered but feel free to comment further if you want to do so.
