### ISSUE TITLE
Please don't elevate privileges in *-cli

### ISSUE THREAD

**Issue by rbalint** [mhogomchungu/zuluCrypt#4]
Please don't use setresuid() & setgroups() in the cli commands.
If the SETUID bit is set on the binaries it is obsolete, otherwise it makes commands which would work without extra privileges fail:
rbalint@chaos:~/projects/deb/zulucrypt.git$ zuluCrypt-cli -A
ERROR: setgroups() failed: Operation not permitted
rbalint@chaos:~/projects/deb/zulucrypt.git$ fakeroot zuluCrypt-cli -A
/dev/sdb1
/dev/sdb2

**Comment by mhogomchungu** [comment]
I should probably update this bug report with new info.

somebody is working on a debian and ubuntu package that will allow zuluCrypt to run without the CLI components being suid root.This is done by starting GUI components already elevated through pkexec tool.

These links maybe useful in finding out more about what i just said:

https://packages.debian.org/source/sid/zulucrypt

https://github.com/marciosouza20/zulucrypt

**Comment by mailinglists35** [comment]
I don't know if this is related but zulucrypt refuses to run as root on debian bookworm

````
user@debian:~$ sudo -i
root@debian:~# zuluCrypt-cli -O -d /dev/sda1 -e ro
ERROR: Only root user can perform this operation
````

**Comment by mailinglists35** [comment]
veracrypt works just fine using `veracrypt --text -k "" --pim=0  --protect-hidden=no --filesystem=none --slot=10`

**Comment by mhogomchungu** [comment]
```
[ink@localhost ~]$ sudo -i
[root@localhost ~]# zuluCrypt-cli -O -d /root/img -e ro
ERROR: Only root user can perform this operation
[root@localhost ~]# 
```

```
[ink@localhost ~]$ su
Password: 
[root@localhost ink]# zuluCrypt-cli -O -d /root/img -e ro
Enter passphrase: 
SUCCESS: plain volume opened successfully
[root@localhost ink]# 
```
It does not work with sudo here too and i am using a distro that is not derived from debian.

From memory, zuluCrypt tracks effective user id and i suspect sudo is failing here.

**Comment by rocketraman** [comment]
> It does not work with sudo here too and i am using a distro that is not derived from debian.

Same problem on Fedora 39.

**Comment by rocketraman** [comment]
run0 on Fedora 41 has the same problem. I've created #221 as a follow-up.
