### ISSUE TITLE
canonicalize_file_name function in stdlib

### ISSUE THREAD

**Issue by rapgro** [mhogomchungu/zuluCrypt#41]
In Fedora we have the canonicalize_file_name function in stdlib. What security flaws do you see? Can we apply a patch?

glibc-2.23.90-30.fc25
glibc-2.23.1-8.fc24
glibc-2.22-17.fc23

```
> grep -R canonicalize_file_name  /usr/include/
/usr/include/stdlib.h:extern char *canonicalize_file_name (const char *__name)

```

```
/*
 * This routine is part of libc.  We include it nevertheless,
 * since the libc version has some security flaws.
 *
 * TODO: use canonicalize_file_name() when exist in glibc
 */

```
zuluCrypt-5.0.0/zuluCrypt-cli/lib/canonicalize/canonicalize.c
zuluCrypt-5.0.0/zuluCrypt-cli/lib/canonicalize/canonicalize.h

**Comment by mhogomchungu** [comment]
I see none.

Somebody suggested it when i started and i found their arguments unconvincing but i went along with them because i did not want to be accused of not caring about security.

You can apply the patch and i think i will remove this internal version and go with glibc one before i make the next release.

**Comment by mhogomchungu** [comment]
The one i provide and the standard one behave differently.

I will make a patch shortly and send it to you.

**Comment by mhogomchungu** [comment]
I just sent you a patch,can you confirm that you got it as i may have sent it to somebody else thinking its you.

**Comment by mhogomchungu** [comment]
The patch is also here[1][2] for those who will read this bug report.

[1] https://github.com/mhogomchungu/random_stuff/blob/master/zuluCrypt.patch
[2] https://raw.githubusercontent.com/mhogomchungu/random_stuff/master/zuluCrypt.patch

**Comment by rapgro** [comment]
This?
https://github.com/mhogomchungu/zuluCrypt/commit/b93fdecfff2609b9b63e89c3b1a48a1c237e5253
raw: https://github.com/mhogomchungu/zuluCrypt/commit/b93fdecfff2609b9b63e89c3b1a48a1c237e5253.patch
