### ISSUE TITLE
desktop files

### ISSUE THREAD

**Issue by rapgro** [mhogomchungu/zuluCrypt#42]
`
$ desktop-file-validate /home/builder/rpmbuild/BUILDROOT/zulucrypt-5.0.0-2.fc24.x86_64/usr/share/applications/zuluCrypt.desktop /home/builder/rpmbuild/BUILDROOT/zulucrypt-5.0.0-2.fc24.x86_64/usr/share/applications/zuluMount.desktop
`

/home/builder/rpmbuild/BUILDROOT/zulucrypt-5.0.0-2.fc24.x86_64/usr/share/applications/zuluCrypt.desktop: error: (will be fatal in the future): value "zuluCrypt.png" for key "Icon" in group "Desktop Entry" is an icon name with an extension, but there should be no extension as described in the Icon Theme Specification if the value is not an absolute path

/home/builder/rpmbuild/BUILDROOT/zulucrypt-5.0.0-2.fc24.x86_64/usr/share/applications/zuluCrypt.desktop: warning: value "" for key "Path" in group "Desktop Entry" does not look like an absolute path

/home/builder/rpmbuild/BUILDROOT/zulucrypt-5.0.0-2.fc24.x86_64/usr/share/applications/zuluCrypt.desktop: hint: value item "Security" in key "Categories" in group "Desktop Entry" can be extended with another category among the following categories: Settings, or System

/home/builder/rpmbuild/BUILDROOT/zulucrypt-5.0.0-2.fc24.x86_64/usr/share/applications/zuluMount.desktop: error: (will be fatal in the future): value "zuluMount.png" for key "Icon" in group "Desktop Entry" is an icon name with an extension, but there should be no extension as described in the Icon Theme Specification if the value is not an absolute path

/home/builder/rpmbuild/BUILDROOT/zulucrypt-5.0.0-2.fc24.x86_64/usr/share/applications/zuluMount.desktop: warning: value "" for key "Path" in group "Desktop Entry" does not look like an absolute path

/home/builder/rpmbuild/BUILDROOT/zulucrypt-5.0.0-2.fc24.x86_64/usr/share/applications/zuluMount.desktop: hint: value item "Security" in key "Categories" in group "Desktop Entry" can be extended with another category among the following categories: Settings, or System

**Comment by mhogomchungu** [comment]
```
/home/builder/rpmbuild/BUILDROOT/zulucrypt-5.0.0-2.fc24.x86_64/usr/share/applications/zuluMount.desktop: hint: value item "Security" in key "Categories" in group "Desktop Entry" can be extended with another category among the following categories: Settings, or System
```

How do i silence the above? All my attempts have failed and google isnt very helpful.

**Comment by rapgro** [comment]
Maybe use System;Security in Categories. 

Hints are not fatal for desktop-file-validate. Other issues are fixed in latest commit. Thanks!
