### ISSUE TITLE
Archlinux AUR: Please provide proper hashsums

### ISSUE THREAD

**Issue by sonicou** [mhogomchungu/zuluCrypt#45]
The PKGBUILD file in the archkinux aur repository uses md5 the verify package integrety.
Please change this to sha256 to provide a secure alternative.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=zulucrypt

**Comment by mhogomchungu** [comment]
I am not the maintainer of zuluCrypt package on arch and hence there is nothing i can do,

Will write an email to the maintainer and pass along your request.

**Comment by mhogomchungu** [comment]
The maintainer already added sha256 checksum.
