### ISSUE TITLE
How to open a plain dm-crypt volume with an offset inside of a LUKS container?

### ISSUE THREAD

**Issue by morfikov** [mhogomchungu/zuluCrypt#48]
I have one partition on my SD card. I've created a LUKS container, in which I placed the EXT4 filesystem. There's also a plain dm-crypt container stored somewhere in the middle of the partition. I know that I use EXT4 instead of FAT, but I shrinked the filesystem before placing files there, so the data stays at the beginning of the drive. After that I enlarged the filesystem so it covers all the partition.. The purpose of this setup is to destroy the hidden dm-crypt volume if someone starts to use the cover filesystem for some reason.

 Anyways, there's the following info in the changelog:

> -- add support for creating a "plain dm-crypt" volume at a "none zero offset".This type of volume is useful as a  "poor man's version of a hidden volume feature in TrueCrypt and VeraCrypt".Best thing about this type of hidden volume is that the outer volume can be anything including an "exposed file system".Currently,only zuluMount-gui can open this type of volume by clicking "options" followed by "Set Volume Offset" on the mounting dialog prompt.

I wanted to test this feature, but it looks that it doesn't support my setup. Here's the main zuluMount window:

![2016-10-28-15 34 11_zulumount](https://cloud.githubusercontent.com/assets/3797768/19808220/0dc2b3be-9d24-11e6-80a6-0455f2db99ff.png)

The dm-crypt volume is in sdb1, but when I want to mount it:

![2016-10-28-15 29 16_mount a luks volume in -dev-sdb1](https://cloud.githubusercontent.com/assets/3797768/19808247/364b5462-9d24-11e6-9066-3d4b010624fe.png)

It thinks that it's a LUKS container, which is true, but it is also unable to give me an option to open the hidden dm-crypt volume. I can set an offset in the options, but I don't think it works as it should:

![2016-10-28-15 29 25_zulumount](https://cloud.githubusercontent.com/assets/3797768/19808285/723410c2-9d24-11e6-83a9-7d43477ae35d.png)

Is there a way to solve this problem?

**Comment by mhogomchungu** [comment]
I just tested here and it worked.

Enter the plain dm-crypt volume password in the "Key" field on the second image above and then enter the volume offset on the third image above.

What error do you get if the above does not work? What value of "offset" did you use? How did you create your plain dm-crypt volume "at a none zero offset"? Maybe there is a mismatch between how zuluMount handles the offset and how the way you created the volume handles it,

**Comment by morfikov** [comment]
Your steps dont't work. I've tried them even before (first dots are the password, second ones are the offset). 

![2016-10-28-17 11 06_zulumount](https://cloud.githubusercontent.com/assets/3797768/19811442/add74c90-9d31-11e6-92f4-3b9bb69bdb5a.png)

I just get a message that the volume can't be opened with the presented key.

![2016-10-28-17 11 31_zulumount](https://cloud.githubusercontent.com/assets/3797768/19811447/b6957e60-9d31-11e6-9203-da4d3be29e1f.png)

I'm using a number of 512 bytes sectors, the same that `cryptsetup` accepts in `--offset=`

The dm-crypt volume was created in the following way:

`# cryptsetup --cipher aes-xts-plain64 --key-size 512 --hash sha512 --iter-time 5000 --verify-passphrase --verbose open --type=plain /dev/sdb1 sdb1 --offset=655360`

It's just for testing purposes only.

**Comment by mhogomchungu** [comment]
zuluCrypt only works with plain dm-crypt volumes that use "aes-cbc-essiv:sha256" cipher and 32bytes/256 bits keysize[1] and currently,there is no way to change these.

"--iter-time" is not used with plain dm-crypt as the effective key is just a "ripemd160" hash.

[1] https://github.com/mhogomchungu/zuluCrypt/blob/5b0b178787e9c71afa5c0433f17c0b7912948c73/zuluCrypt-cli/lib/open_plain.c#L112

**Comment by morfikov** [comment]
Too bad. :/

**Comment by mhogomchungu** [comment]
If all your plain dm-crypt volumes are created with those options,then you can patch zuluCrypt to make it use those options. The line i highlighted above and the 93rd line are the only two places you will need to modify.

**Comment by morfikov** [comment]
I think I'll stay with the defaults, but good to know why it failed to open.

**Comment by mhogomchungu** [comment]
git version can now unlock your plain dm-crypt volume that uses non default crypto properties.

Supported options are listed here[1], you can add/remove options by modifying 
```~/.zuluCrypt/plainDmCryptOptions``` config file.

[1] https://github.com/mhogomchungu/zuluCrypt/blob/08a37338e484f8d48f74fa74495675549b3b6002/zuluCrypt-gui/utility.cpp#L1950

**Comment by mhogomchungu** [comment]
zuluCrypt-gui git should now be able to fully support your use cases with plain dm-crypt volumes.

The git version can now do as documented here: https://github.com/mhogomchungu/zuluCrypt/blob/980b36e694335da8214885980942f34307a6e5a6/changelog#L261
