### ISSUE TITLE
Add a switch to show password in the password field

### ISSUE THREAD

**Issue by pspot2** [mhogomchungu/zuluCrypt#55]
Hi Francis,

I've been a long-time user of zuluCrypt and find it simply awesome. Do you accept donations?

In my HTPC setup I use a flatscreen TV as my monitor and sit approx. 5 meters away from it. I also use a wireless mini-keyboard to operate the PC (and zuluCrypt on it). The signal from this keyboard is unfortunately not always reliable, therefore symbols or keypresses might get lost. This is easily identifiable when typing a text that I can see. But when typing a masked password into zuluCrypt, I cannot see whether my Shift keypresses worked properly and thus whether I entered a correct password. Things get worse because in my case I'm opening a VeraCrypt volume, which - if the password was wrong - takes around 1 minute 30 secs in my case to get to the error message about the wrong password. I do not want to use a workaround of typing the password into a text editor and then copy-pasting it via the paste buffer into the password field of zuluCrypt.

Would it be possible to implement a switch to unmask the password in the password field? kdesu, for example, uses an eye symbol for that in the right part of the field.

Thanks very much.

**Comment by mhogomchungu** [comment]
I am in Tanzania(Somewhere on the eastern side of africa) and last time i checked,paypal does not work here making it impossible to accept donations.

The git version has the switch you requested, the new gui window in zuluCrypt-gui looks like below

![screenshot_20170207_185318](https://cloud.githubusercontent.com/assets/3496115/22702058/8661d574-ed70-11e6-9574-90cd60c9b1ee.png)
