### ISSUE TITLE
Can't umount luks cointainer file

### ISSUE THREAD

**Issue by sokeeflo** [mhogomchungu/zuluCrypt#57]
Hi!

I created luks container file, size=100mb from `zuluCrypt-gui` in `/home/user`

After I mount it from `zuluMount-gui` the program hangs.
Here's `strace` output:

After I kill the process, my container is successfully mounted but it's mountpoint in `zuluMount-gui` is incorectly showed as `Nil` and when i try umount it has no effect. It's the same when I try to mount it from `zuluMount-Cli` first.

When I try umount from `zuluMount-Cli` it shows error:
`ERROR: Close failed, volume is unmounted but could not close mapper,advice to close it manually`
but the volume is still mounted, I can acces files inside.

When I try `sudo cryptsetup close /dev/dm-0` it shows error:
`evice-mapper: remove ioctl on zuluCrypt-1000-NAAN-vault-272093110  failed: Device or resource busy`

Sometimes after moving back and forth I am able to close device succesfully from `cryptsetup` command but I can't 100% reproduce it.

I tried build with `DHOMEMOUNTPREFIX=true` but I have the same issues.

BTW: When I mount container in `/run/media/private/user`, the `user` folder has always permissions set like uid=gid, which isn't always the case so the gid could be nonexistent wrongly attached.

**Comment by mhogomchungu** [comment]
what version of zuluCrypt are you using and you got it from where

what is the output of the following commands?

``` 
stat ~/.zuluCrypt
stat ~/.zuluCrypt-socket
```

**Comment by sokeeflo** [comment]
I tested current master git and 5.1 stable on Archlinux,
Here's stat output:
```
stat ~/.zuluCrypt 
File: /home/user/.zuluCrypt
Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 806h/2054d      Inode: 13213831    Links: 2
Access: (0777/drwxrwxrwx)  Uid: ( 1000/      user)   Gid: (  100/   users)
Access: 2017-04-22 14:34:22.623818042 +0200
Modify: 2017-04-23 20:03:59.840037610 +0200
Change: 2017-04-23 20:03:59.840037610 +0200
Birth: -
stat ~/.zuluCrypt-socket
File: /home/user/.zuluCrypt-socket
Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 806h/2054d      Inode: 13213834    Links: 2
Access: (0777/drwxrwxrwx)  Uid: ( 1000/      user)   Gid: ( 1000/      user)
Access: 2017-04-22 14:34:22.623818042 +0200
Modify: 2017-04-23 20:04:09.176037738 +0200
Change: 2017-04-23 20:04:09.176037738 +0200
Birth: -
```
Also when I start `zuluMount-gui` it shows message:
`Reading partition properties took longer than expected and operation was terminated,click refresh to try again`

**Comment by mhogomchungu** [comment]
What is the output of the following command

```
zuluCrypt-cli   --test
```

**Comment by sokeeflo** [comment]
```
zuluCrypt-cli --test
creating a testing image file
creating a testing image file
creating a testing image file
creating a keyfile
creating a keyfile

create a luks type volume using a key: PASSED

check if a luks volume is a luks volume: PASSED

create luks header backup: PASSED

restore luks header from backup: PASSED

create a plain type volume using a key: PASSED

create a tcrypt type volume using a key: PASSED

open a plain volume with a key: PASSED
closing a plain volume: FAILED
ERROR: Close failed, volume is unmounted but could not close mapper,advice to close it manually
```

Addition to my previous comment:
As you can see from `stat`, `~/.zuluCrypt-socket` has wrong GID (correct gid for my user is `users:100`, as `user:1000` don't exist in Arch by default. Also both files doesn't honor default `umask` value of `022` so correct permissions should be `755` instead of `777` but I'm not sure if it's related to main issue as adjusting it manually didn't change anything.

**Comment by mhogomchungu** [comment]
```
Also when I start zuluMount-gui it shows message:
Reading partition properties took longer than expected and
 operation was terminated,click refresh to try again
```
zuluMount-gui calls ```zuluMount-cli -l``` and expects a response within 10 seconds.

What is the output of ```zuluMount-cli -l```?

```
open a plain volume with a key: PASSED
closing a plain volume: FAILED
ERROR: Close failed, volume is unmounted but could not close
 mapper,advice to close it manually
```

After the above command fail and before you attempt to clean up the mess,run the following command and post its output: ``` cat /proc/self/mountinfo```

There is interference by somebody probably by a combination of udisks and your file manager/desktop environment. Every time a zuluCrypt encryption mapper shows up,udisks mounts it and that causes problems. I solved this problem a long time ago here[1]. According to the code,you will get the error you are getting in two scenario,you use home point path,zuluCrypt failed to unmount atleast one of the extra mount points.

What desktop environment and file manager are you using?

[1] https://github.com/mhogomchungu/zuluCrypt/blob/58bfbd24f04ffcd1820f20135e191fb547a8bf9e/zuluCrypt-cli/lib/unmount_volume.c#L180

**Comment by mhogomchungu** [comment]
```
As you can see from stat, ~/.zuluCrypt-socket has wrong 
GID (correct gid for my user is users:100, as user:1000 don't exist 
in Arch by default. Also both files doesn't honor default umask value
 of 022 so correct permissions should be 755 instead of 777 but I'm not 
sure if it's related to main issue as adjusting it manually didn't change anything.
```
Current git master will not change change gid and hence they will be whatever value mkdir() sets them.

permissions are 777 on those folders on purpose. What matters is that the folders are writable.

**Comment by sokeeflo** [comment]
```
zuluMount-cli -l
/dev/sda5       /       ext4    ROOT
/dev/sda8       /var    ext4    VAR
/dev/sda6       /home   ext4    HOME
/dev/sda1       /boot/efi       vfat
/tmp/zuluCrypt-plainTestVolume (deleted)        Nil     Nil     Nil     10.0 MB Nil
```
`cat /proc/self/mountinfo`
[mountinfo.txt](https://github.com/mhogomchungu/zuluCrypt/files/952323/mountinfo.txt)


I use KDE plasma 5.9.4, Dolphin filemanager. I set my `TMPDIR=/home/user/tmp` instead of default `/tmp`.

I tried newest build and the GID issues are even worse:
`/run/media/private` has `UID=root GID=1000,` before was `UID=root GID=root`
`/run/media/private/user` has `UID=user GID=1000,` before was `UID=user GID=1000` (no change, correct GID=100)

Maybe the correct GID has to be guessed from `/etc/passwd`?

**Comment by mhogomchungu** [comment]
Try the git version to see if the group id issue is resolved.

**Comment by sokeeflo** [comment]
Yes, GID looks correct now, thanks! :smile:

As for the main issue it looks that zuluCrypt thinks my mountpoint is `/tmp/zuluCrypt-plainTestVolume` when it's really in `/run/media/private/user/zuluCrypt-MountPoint`.

I can umount it by `sudo umount /run/media/private/user/zuluCrypt-MountPoint` and then close by `zuluCrypt-cli -q -d /path/to/file`

In real case mountpoint is in `/run/media/private/user/$mountpoint` but zuluCrypt can't detect it at all.

**Comment by mhogomchungu** [comment]
"/tmp/zuluCrypt-plainTestVolume" is a test volume file created when you run "zuluCrypt-cli --test".

It makes no sense why you are getting that error,if the problem was multiple mount points,zuluCrypt would have said so[1]. Going to ask other arch linux users[2] if they can reproduce your problem.

[1] https://github.com/mhogomchungu/zuluCrypt/blob/9055bcfbc79b735972193b2586ab6a082d85f93c/zuluCrypt-cli/bin/close_volume.c#L42

[2] https://aur.archlinux.org/packages/zulucrypt/

**Comment by Salan54** [comment]
Hi @mhogomchungu
Here is the output on my Arch machine
uname -a : Linux rdc2010 4.10.10-1-ARCH #1 SMP PREEMPT Wed Apr 12 19:10:48 CEST 2017 i686 GNU/Linux

```
[alain@rdc2010 ~]$ zuluCrypt-cli   --test
creating a testing image file
creating a testing image file
creating a testing image file
creating a keyfile
creating a keyfile

create a luks type volume using a key: PASSED

check if a luks volume is a luks volume: PASSED

create luks header backup: PASSED

restore luks header from backup: PASSED

create a plain type volume using a key: PASSED

create a tcrypt type volume using a key: PASSED

open a plain volume with a key: PASSED
closing a plain volume: PASSED

open a plain volume with a keyfile: PASSED
closing a plain volume: PASSED

open a tcrypt volume with a key: PASSED
closing a tcrypt volume: PASSED

open a plain volume using a plugin: PASSED
closing a plain volume: PASSED

open a luks volume with a key: PASSED
closing a luks volume: PASSED

open a luks volume with a keyfile: PASSED
closing a luks volume: PASSED

open a luks volume using a plugin: PASSED
closing a luks volume: PASSED

check key slots in use: 30000000

add a key to a luks volume using a key and a key: PASSED
add key to luks volume using keyfile and keyfile: PASSED
add key to luks volume using passphrase and keyfile: PASSED
add key to luks volume using keyfile and passphrase: PASSED

check key slots in use: 11111000

remove a key from a luks volume using a key: PASSED
remove a key from a luks volume using a keyfile: PASSED
check key slots in use: 01011000

check if there are no opened mappers: PASSED

```

**Comment by sokeeflo** [comment]
> "/tmp/zuluCrypt-plainTestVolume" is a test volume file created when you run "zuluCrypt-cli --test".

Does It mean `zuluCrypt-cli --test` shouldn't touch `/run/media` dir at all? Maybe something "steals" the device and mount it in `/run/media` instead but those permission issues point to `zuluCrypt-cli --test` directly.

**Comment by sokeeflo** [comment]
I made some additional logs with `python-maybe`  and `strace` tools.
[python-maybe.txt](https://github.com/mhogomchungu/zuluCrypt/files/955347/python-maybe.txt)
[strace.txt](https://github.com/mhogomchungu/zuluCrypt/files/955348/strace.txt)

Not that at the end it tried to delete `/home/user/zuluCrypt-MountPoint` dir but it didn't attempt to create it at first nor it didn't attempt to create `/tmp/zuluCrypt-MountPoint` too.

**Comment by sokeeflo** [comment]
Ok, running it under independent root console session succeeds. Switching to root inside my user session isn't enough. I have no idea what's the blocker here.

**Comment by mhogomchungu** [comment]
The above output from "Salan54" says this is a local problem and a general problem on all arch install.

```zuluCrypt-cli --test``` creates 3 test files named: 
1. "/tmp/zuluCrypt-luksTestVolume",
2. "/tmp/zuluCrypt-plainTestVolume",
3. "/tmp/zuluCrypt-tcryptTestVolume".

It then calls zuluCrypt-cli on these test file to create encrypted volumes in then,add keys,remove keys,take header backup and unlocking them and locking. All in the process of making sure zuluCrypt functionality works as expected.

For "/tmp/zuluCrypt-plainTestVolume",on unlocking success it mounts its file system "/run/media/private/<user>/zuluCrypt-plainTestVolume"

These outputs will not show the problem because the problem is on the encryption mapper,something else other that zuluCrypt is holding it and my google searches have failed to show me how i can found out how to get a list of processes that have a hold on a block device.

**Comment by sokeeflo** [comment]
Hm, but when I can unmount device manually, doesn't it means that nothing is blocking the device?
The correct way should be:
`open -> mount -> unmount -> close`
but it looks like `zuluCrypt-cli`do:
`open -> mount -> close`

Also the mountpoint is available clearly in `/proc/self/mountinfo` but `zuluCrypt-cli` always show `Nil` even, as you can see in logs it consults  `/proc/self/mountinfo` couple of times.

I'm sorry to sorry to disturb you about this specific issue. I just feel bad that I can't use your great soft :smile:

**Comment by mhogomchungu** [comment]
This is how it works:

Lets say you have a volume at "/dev/sdc1".

Unlocking the volume involves two steps:

1.  Creating an encryption mapper against the volume at "/dev/mapper/zuluCrypt-NAAN-sdc1-234232321".

2. Mounting the file system on the encryption mapper.

Locking the volume involves two steps:

1. Unmount all mount points that are opened against the encryption mapper.

2. Tear down the encryption mapper.

"/proc/self/mountinfo" contains information about mounted volumes and "/dev/mapper" contains information about encryption mappers.

How did you build zuluCrypt? Somebody a long time ago had problems using zuluCrypt on arch and the problem was due to them using some sort of a hardened compiler.

**Comment by sokeeflo** [comment]
I tried changing compilation flags without results. As I post earlier running it with pure root account success so compilation shouldn't be issue here.

I still don't get how it's possible that zuluCrypt can't detect mountpoint whet it's available in plain. As a setuid binary it should cross any boundaries anyway.
