### ISSUE TITLE
ZuluCrypt-gui freezes when creating "encrypted container in a  file"

### ISSUE THREAD

**Issue by rheinz96** [mhogomchungu/zuluCrypt#58]
Hey,

i currently use **Ubuntu 16.04** with **Unity** desktop. 

When I select **"creating a encrypted container in a file"** in **zuluCrypt-gui,** the dialog box opens normally.

![grafik](https://cloud.githubusercontent.com/assets/28300143/25618566/b8aadd3c-2f47-11e7-9c88-94783d997d18.png)

________________________________
Now, when I clicking "create", the dialog window **greys out** and **nothing happens** anymore. Then I had to kill the process from terminal. Sometimes I get the error message _**"could not open cryptographic back end to generate random data"**_ but most of the times, the window just does nothing.

![grafik](https://cloud.githubusercontent.com/assets/28300143/25618646/118c17a4-2f48-11e7-9fb6-98bf9dbe5051.png)

I can't even close the program via "cancel" button. The popup question dialog "Are you sure ...." is visible, but doesn't react.

![grafik](https://cloud.githubusercontent.com/assets/28300143/25618735/62e9e540-2f48-11e7-94a8-fb2840259c20.png)

I installed the program via the [PPA](https://launchpad.net/~hda-me/+archive/ubuntu/zulucrypt), but I also installed it with the **.deb** src files from the [official website](https://mhogomchungu.github.io/zuluCrypt/).

Is there a way to solve this problem or does anyone have **similar issues**?

**Comment by mhogomchungu** [comment]
Which one are you using now? If from the official website then open the termnial and then run these two commands and try again.
```
sudo rm -rf ~/.zuluCrypt
sudo rm -rf ~/zuluCrypt-socket
```

**Comment by rheinz96** [comment]
At the moment, I use the package from the official website (zuluCrypt-5.1.0-ubuntu-16.04-Xenial_Xerus.tar.xz)

Unfortunately, after deleting the two directories, the error still exists.

**Comment by mhogomchungu** [comment]
That is strange,

open the termnial and run the following command and post its output

```
zuluCrypt-cli  --test
```

**Comment by rheinz96** [comment]
**Output**

> WARNING: "loop" kernel module does not appear to be loaded,
> tests and opening of encrypted containers in files will fail if the module was not built into the kernel
> 
> creating a testing image file
> creating a testing image file
> creating a testing image file
> creating a keyfile
> creating a keyfile
> 
> create a luks type volume using a key: 

Now, the test stops at _"create a luks type volume using a key"_

**Comment by mhogomchungu** [comment]
Are you on a new system?
Have you ever used hard drive encryption on your system?

cryptsetup tool does not appear to work as expected your system.

what is the output of ```lsmod``` command.

**Comment by rheinz96** [comment]
I use 16.04 for over a half year now. But I'm new in encryption and want to learn something about it, because i heard a lot of good reviews about your tool ;)

<details>
<summary>lsmod</summary>

- Module                  Size  Used by
- algif_skcipher         20480  0
- af_alg                 16384  1 algif_skcipher
- dm_crypt               28672  3
- drbg                   32768  1
- ansi_cprng             16384  0
- ctr                    16384  1
- ccm                    20480  1
- ipt_MASQUERADE         16384  1
- nf_nat_masquerade_ipv4    16384  1 ipt_MASQUERADE
- xt_conntrack           16384  1
- ipt_REJECT             16384  2
- nf_reject_ipv4         16384  1 ipt_REJECT
- xt_tcpudp              16384  4
- iptable_filter         16384  1
- nf_nat_h323            20480  0
- nf_conntrack_h323      77824  1 nf_nat_h323
- nf_nat_pptp            16384  0
- nf_nat_proto_gre       16384  1 nf_nat_pptp
- nf_conntrack_pptp      20480  1 nf_nat_pptp
- nf_conntrack_proto_gre    16384  1 nf_conntrack_pptp
- nf_nat_tftp            16384  0
- nf_conntrack_tftp      16384  1 nf_nat_tftp
- nf_nat_sip             20480  0
- nf_conntrack_sip       28672  1 nf_nat_sip
- nf_nat_irc             16384  0
- nf_conntrack_irc       16384  1 nf_nat_irc
- nf_nat_ftp             16384  0
- nf_conntrack_ftp       20480  1 nf_nat_ftp
- iptable_nat            16384  1
- nf_conntrack_ipv4      16384  2
- nf_defrag_ipv4         16384  1 nf_conntrack_ipv4
- nf_nat_ipv4            16384  1 iptable_nat
- nf_nat                 24576  9 nf_nat_ftp,nf_nat_irc,nf_nat_sip,nf_nat_proto_gre,nf_nat_h323,nf_nat_ipv4,nf_nat_pptp,nf_nat_tftp,nf_nat_masquerade_ipv4
- nf_conntrack          106496  18 nf_nat_ftp,nf_nat_irc,nf_nat_sip,nf_conntrack_proto_gre,nf_nat,nf_nat_h323,nf_nat_ipv4,nf_nat_pptp,nf_nat_tftp,xt_conntrack,nf_nat_masquerade_ipv4,nf_conntrack_ftp,nf_conntrack_irc,nf_conntrack_sip,nf_conntrack_h323,nf_conntrack_ipv4,nf_conntrack_pptp,nf_conntrack_tftp
- ip_tables              24576  2 iptable_filter,iptable_nat
- x_tables               36864  6 ip_tables,xt_tcpudp,ipt_MASQUERADE,xt_conntrack,iptable_filter,ipt_REJECT
- rfcomm                 69632  0
- rtsx_usb_ms            20480  0
- memstick               20480  1 rtsx_usb_ms
- bnep                   20480  2
- arc4                   16384  2
- binfmt_misc            20480  1
- nls_iso8859_1          16384  1
- joydev                 20480  0
- hid_multitouch         20480  0
- acer_wmi               20480  0
- sparse_keymap          16384  1 acer_wmi
- uvcvideo               90112  0
- videobuf2_vmalloc      16384  1 uvcvideo
- videobuf2_memops       16384  1 videobuf2_vmalloc
- videobuf2_v4l2         28672  1 uvcvideo
- videobuf2_core         36864  2 uvcvideo,videobuf2_v4l2
- v4l2_common            16384  1 videobuf2_v4l2
- videodev              176128  4 uvcvideo,v4l2_common,videobuf2_core,videobuf2_v4l2
- intel_rapl             20480  0
- x86_pkg_temp_thermal    16384  0
- media                  24576  2 uvcvideo,videodev
- intel_powerclamp       16384  0
- snd_hda_codec_hdmi     53248  1
- kvm_intel             172032  0
- snd_hda_codec_realtek    86016  1
- kvm                   540672  1 kvm_intel
- btusb                  45056  0
- snd_hda_codec_generic    77824  1 snd_hda_codec_realtek
- btrtl                  16384  1 btusb
- btbcm                  16384  1 btusb
- btintel                16384  1 btusb
- snd_hda_intel          40960  7
- bluetooth             520192  29 bnep,btbcm,btrtl,btusb,rfcomm,btintel
- ath10k_pci             45056  0
- ath10k_core           311296  1 ath10k_pci
- irqbypass              16384  1 kvm
- snd_hda_codec         135168  4 snd_hda_codec_realtek,snd_hda_codec_hdmi,snd_hda_codec_generic,snd_hda_intel
- snd_hda_core           73728  5 snd_hda_codec_realtek,snd_hda_codec_hdmi,snd_hda_codec_generic,snd_hda_codec,snd_hda_intel
- ath                    32768  1 ath10k_core
- crct10dif_pclmul       16384  0
- snd_hwdep              16384  1 snd_hda_codec
- mac80211              737280  1 ath10k_core
- crc32_pclmul           16384  0
- snd_pcm               106496  5 snd_hda_codec_hdmi,snd_hda_codec,snd_hda_intel,snd_hda_core
- aesni_intel           167936  9
- snd_seq_midi           16384  0
- cfg80211              565248  3 ath,mac80211,ath10k_core
- snd_seq_midi_event     16384  1 snd_seq_midi
- aes_x86_64             20480  1 aesni_intel
- snd_rawmidi            32768  1 snd_seq_midi
- lrw                    16384  1 aesni_intel
- snd_seq                69632  2 snd_seq_midi_event,snd_seq_midi
- gf128mul               16384  1 lrw
- input_leds             16384  0
- glue_helper            16384  1 aesni_intel
- snd_seq_device         16384  3 snd_seq,snd_rawmidi,snd_seq_midi
- snd_timer              32768  2 snd_pcm,snd_seq
- ablk_helper            16384  1 aesni_intel
- cryptd                 20480  5 aesni_intel,ablk_helper
- serio_raw              16384  0
- snd                    81920  24 snd_hda_codec_realtek,snd_hwdep,snd_timer,snd_hda_codec_hdmi,snd_pcm,snd_seq,snd_rawmidi,snd_hda_codec_generic,snd_hda_codec,snd_hda_intel,snd_seq_device
- soundcore              16384  1 snd
- mei_me                 36864  0
- mei                    98304  1 mei_me
- lpc_ich                24576  0
- shpchp                 36864  0
- dell_smo8800           16384  0
- dw_dmac                16384  0
- dw_dmac_core           24576  1 dw_dmac
- i2c_designware_platform    16384  0
- 8250_dw                16384  0
- acpi_pad               20480  0
- tpm_crb                16384  0
- i2c_designware_core    20480  1 i2c_designware_platform
- spi_pxa2xx_platform    24576  0
- mac_hid                16384  0
- coretemp               16384  0
- parport_pc             32768  0
- ppdev                  20480  0
- lp                     20480  0
- parport                49152  3 lp,ppdev,parport_pc
- autofs4                40960  2
- rtsx_usb_sdmmc         28672  0
- rtsx_usb               24576  2 rtsx_usb_sdmmc,rtsx_usb_ms
- hid_generic            16384  0
- usbhid                 49152  0
- i915                 1208320  4
- nouveau              1495040  0
- mxm_wmi                16384  1 nouveau
- ttm                    94208  1 nouveau
- i2c_algo_bit           16384  2 i915,nouveau
- drm_kms_helper        155648  2 i915,nouveau
- ahci                   36864  3
- libahci                32768  1 ahci
- syscopyarea            16384  1 drm_kms_helper
- sysfillrect            16384  1 drm_kms_helper
- sysimgblt              16384  1 drm_kms_helper
- fb_sys_fops            16384  1 drm_kms_helper
- r8169                  81920  0
- drm                   364544  7 ttm,i915,drm_kms_helper,nouveau
- mii                    16384  1 r8169
- wmi                    20480  3 acer_wmi,mxm_wmi,nouveau
- fjes                   28672  0
- i2c_hid                20480  0
- video                  40960  3 i915,acer_wmi,nouveau
- sdhci_acpi             16384  0
- hid                   118784  4 i2c_hid,hid_multitouch,hid_generic,usbhid
- sdhci                  45056  1 sdhci_acpi
- 

</details>

**Comment by mhogomchungu** [comment]
Your main issue is with cryptsetup and not with zuluCrypt. zuluCrypt will work as expected only when cryptsetup does.

Let see if i can figure out what is wrong with your cryptsetup.

run these commands and post their output

```
truncate -s 10M test.img
sudo cryptsetup --debug luksFormat test.img
```
There are two more commands in the sequence but lets start with those two.

Note that you will be asked to type "YES" and then asked for a password twice,pick any password

**Comment by rheinz96** [comment]
Okay, this worked without problems.

<details>
<summary>Output</summary>

![grafik](https://cloud.githubusercontent.com/assets/28300143/25623896/3d73791a-2f58-11e7-8433-a294bd4f730c.png)
</details>

**Comment by mhogomchungu** [comment]
Then to finish the test with the remaining two commands

```
sudo cryptsetup --debug luksOpen test.img xxx
sudo cryptsetup --debug luksClose xxx
```

**Comment by rheinz96** [comment]
Looks like cryptsetup hangs up again. It prints no more output since 5min.

Output first command: _(sudo cryptsetup --debug luksOpen test.img xxx)_
![grafik](https://cloud.githubusercontent.com/assets/28300143/25625193/2b792dc8-2f5c-11e7-9899-46fd156acd35.png)

**Comment by mhogomchungu** [comment]
This post[1] seems to have pointers to the problem and the problem seems to be a missing "55-dm.rules" file. 

[1] https://serverfault.com/questions/739531/arch-cryptsetup-hangs-on-waiting-for-zero

**Comment by rheinz96** [comment]
Finally, I got it! Thank you very much for your help :+1: 

Indeed there was missing **"55-dm.rules"** in /lib/udev/rules.d

After installing   `sudo apt install dmsetup`   the file has been created automatically. 
Dmsetup wasn't installed by default.

Now, _**cryptsetup**_ works properly and I can create files with _**zuluCrypt**_ :smile: 

Thank you for your awesome program!
