### ISSUE TITLE
zuluCrypt-cli and zuluMount-cli no option for mount plain64 aes xts 

### ISSUE THREAD

**Issue by unknown1819** [mhogomchungu/zuluCrypt#62]
Hi,
I check all manuals but i cannot find how to use zuluCrypt-cli to mount/open aes xts plain64 volume command -t plain dont work.

Best regards

**Comment by mhogomchungu** [comment]
zuluCrypt supports 4 types of volumes.
1. LUKS volumes.
2. PLAIN dm-crypt volumes
3. TrueCrypt volumes.
4. VeraCrypt volumes.

Your volume is of what type?

If one of the 3 then the following command should be sufficient since zuluCrypt can tell the difference between them,enter volume password when asked.

If your volume is a veracrypt volume,add ```-t vcrypt``` argument.

```
zuluCrypt-cli -o -d volume.img
```

**Comment by unknown1819** [comment]
its a plain dm-crypt aes.xts-plain64.256.sha1 i dont know where to put this commands its only -t plain option

zuluCrypt-cli -o -d /home/user/Desktop/.../test -t plain aes.xts-plain64.256.sha1 -p $PASSWORD -m mount

**Comment by mhogomchungu** [comment]
try the following line

```
zuluCrypt-cli -o -d /home/user/Desktop/.../test -t aes.xts-plain64.256.sha1.0 -p $PASSWORD -m mount
```

**Comment by unknown1819** [comment]
Working! 

I would like to make automatic bash script with this command to check all passwords from .txt file each password in each line cause i forget my password but i remember some part of that password. If zuluCrypt-cli give me error then try another line from passwords.txt

#!/bin/bash
PASSWORD=passwords.txt
zuluCrypt-cli -o -d /home/user/Desktop/.../test -t aes.xts-plain64.256.sha1.0 -p $PASSWORD -m mount

**Comment by mhogomchungu** [comment]
Try with below script

```
#!/bin/bash

for i in $( cat passwords.txt ); do
	zuluCrypt-cli -o -d /home/user/Desktop/.../test -t aes.xts-plain64.256.sha1.0 -p $i -m mount1>/dev/null
	if [ "$?" == "0" ]
	then
		echo "correct password is: " $i
		break
	else
		echo "failed to unlock with password: " $i
	fi
done
```
You should get output like below:
```
[mtz@ink ~]$ ./script 
failed to unlock with password:  zzz
failed to unlock with password:  xxxd
failed to unlock with password:  rrr
failed to unlock with password:  xxxs
correct password is:  xxx
[mtz@ink ~]$ 
```

**Comment by unknown1819** [comment]
You are AMAZING! Now i can create with John password list txt with my part password what i remember and check them all to recovery my all data omg you save my life! Thank You so much!
