### ISSUE TITLE
[Clang] open a plain volume with a key: FAILED

### ISSUE THREAD

**Issue by fancytenseletters** [mhogomchungu/zuluCrypt#63]
zuluMount fails to open encrypted volumes (plain and luks) when compiled with clang:
```
zuluCrypt-cli --test
creating a testing image file
creating a testing image file
creating a testing image file
creating a keyfile
creating a keyfile

create a luks type volume using a key: PASSED

check if a luks volume is a luks volume: PASSED

create luks header backup: PASSED

restore luks header from backup: PASSED

create a plain type volume using a key: PASSED

create a tcrypt type volume using a key: PASSED

open a plain volume with a key: FAILED
SIGSEGV caught,exiting
```

When compiled with gcc it works.

I tested with:
`clang version 4.0.1 (tags/RELEASE_401/final)`
I tested 5.2 and 5.1 zuluMount versions

**Comment by mhogomchungu** [comment]
works fine here with clang 3.9.1. I always test with clang and gcc.

Can you look at your system logs to see if there was an entry about the crash,the crash could be in zuluCrypt or in one of the libraries it depends on.

**Comment by fancytenseletters** [comment]
There is absolutely nothing in logs. I tried clang 3.5 but it doesn't compile. Clang 4.0 is available in Archlinux if you wan try it.

When I start it from gui and try to mount volume then I see: `SIGSEGV caught,exiting` message but nothing really crashed and app is still functional.

I attached [strace log](https://paste.ubuntu.com/25056051/) of `zuluCrypt-cli --test`, I don't know if it's helpful here but I don't have anything else.

**Comment by mhogomchungu** [comment]
Confirming the problem with clang 4.0.1 on Fedora 25.

**Comment by mhogomchungu** [comment]
The git version has a fix for the bug.

Will appreciate if you can confirm.

**Comment by fancytenseletters** [comment]
I can confirm it work now. Thank you.

**Comment by mhogomchungu** [comment]
Interesting development, i tried to build problematic code with gcc 7.1.0 and it failed to build with below error:

```
[ 23%] Building C object zuluCrypt-cli/CMakeFiles/zuluCrypt-exe.dir/bin/open_volume.c.o
/home/mtz/.projects/zuluCrypt/zuluCrypt-cli/bin/open_volume.c: In function ‘zuluCryptEXEOpenVolume’:
/home/mtz/.projects/zuluCrypt/zuluCrypt-cli/bin/open_volume.c:536:2: error: wrong type argument to unary minus
  - plugin_path = plugin_path + StringLastIndexOfChar_1( plugin_path,'/' ) + 1 ;
  ^
zuluCrypt-cli/CMakeFiles/zuluCrypt-exe.dir/build.make:134: recipe for target 'zuluCrypt-cli/CMakeFiles/zuluCrypt-exe.dir/bin/open_volume.c.o' failed

```

**Comment by fancytenseletters** [comment]
I can't reproduce on my machine.
```
gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 7.1.1 (GCC)
```

**Comment by mhogomchungu** [comment]
It compiled and run fine here with with gcc 7.1.1 on fedora 25.

If you know C,the offending code looked like below:

```
#include<stdio.h>
#include<string.h>

static ssize_t foo()
{
	return -1 ;
}

int main()
{
	char * x = NULL ;

	x = x + foo() + 1 ;

	printf( "%d\n",x ) ;

	if( x == NULL ){

		puts( "1" ) ;
	}else{
		puts( "2" ) ;
	}

	return 0 ;
}
```

On my local test here:

gcc 4.9.2 and 7.1.0 prints "0 1" with and without optimization.

clang 3.9.1 and 4.0.1 prints "0 1" without optimization and "0 2" with optimization.

The crash is due to the NULL check being removed in clang causing a wrong code path to be taken.

This behavior of different compilers or different versions of the same compiler producing different results happen when the compile code has undefined behavior.

**Comment by zj5121** [comment]
This is interesting, I use clang++ 4.0.0:
$ clang++ -O2 test.cc
$ ./a.out
0 2

the  `if (x==NULL)` is removed and directly output '2'.

here is the godbolt compile result:
https://godbolt.org/g/qrk5qd

if compile with -O0, it's good.
