### ISSUE TITLE
Unprivileged version of zuluCrypt

### ISSUE THREAD

**Issue by gutosurrex** [mhogomchungu/zuluCrypt#64]
I know I am probably overlooking several issues, but I wander if it would be possible to have a version of zulucrypt that is "unrooted".

For my use-case, I only need to mount encrypted files into folders (both the files and the folders belong to my `/home/user`. So, in principle it would be possible to do this without admin privileges. Is that out of reach?

Great software, by the way.

**Comment by mhogomchungu** [comment]
What version of zuluCrypt are you using and in what distribution?

The experience you want is the one i offer in zuluCrypt packages i distribute in the project's main page[1]. 

If i have a package for your distribution and version,then uninstall the version of zuluCrypt you are using that you obtained from your distribution and use the one i distribute.

The relevate quote from the main page documentation is:

```
zuluCrypt packages i provide are better than those provided by these distributions
because of the following reasons:

1. My packages do not generated a polkit prompt that requires a root password
   when GUI components are started.

2. My packages provides CLI components that work from a normal user account.
```


[1] https://mhogomchungu.github.io/zuluCrypt/

**Comment by mhogomchungu** [comment]
```
So, in principle it would be possible to do this without admin privileges. Is that out of reach?
```
Not possible.

First, root privileges are required when "converting" your image file to a block device since the kernel infrastructure that deals with block device encryption(dm-crypt) only works with block devices.

Second, dm-crypt requires root privileges to operate.

The version of zuluCrypt i distribute hides above facts while zuluCrypt packages in debian, ubuntu and fedora do not.

**Comment by gutosurrex** [comment]
I currently use the Debian package (see details below). I will soon look into the package you distribute.

Thanks a lot for the feedback!

```
ackage: zulucrypt-gui
Source: zulucrypt
Version: 5.0.2-2
Installed-Size: 1524
Maintainer: Marcio de Souza Oliveira <m.desouza20@gmail.com>
Architecture: amd64
Depends: libblkid1 (>= 2.16), libc6 (>= 2.14), libgcc1 (>= 1:3.0), libgcrypt20 (>= 1.7.0), libpwquality1 (>= 1.1.0), libqt5core5a (>= 5.7.0), libqt5gui5 (>= 5.0.2), libqt5network5 (>= 5.0.2), libqt5widgets5 (>= 5.0.2), libsecret-1-0 (>= 0.7), libstdc++6 (>= 4.5), libzulucryptpluginmanager1.0.0 (>= 5.0.2), zulucrypt-cli
Description-md5: f4172756adcde7533ace4eab972460f8
Homepage: http://mhogomchungu.github.io/zuluCrypt
Tag: uitoolkit::qt
Section: utils
Priority: optional
Filename: pool/main/z/zulucrypt/zulucrypt-gui_5.0.2-2_amd64.deb
Size: 416646
MD5sum: da2478f3bfff7c86d67eb7c38f3f02a2
SHA256: 5df473ccc64e7da425ac764d41e0dea7243bdd82b45ac2fca8e3674b4eb56b5e
```
