### ISSUE TITLE
Don't erase textbox key on failure

### ISSUE THREAD

**Issue by virtuald** [mhogomchungu/zuluCrypt#70]
I have several volumes with different passwords (or variations thereof). As a forgetful user, I often find myself iterating through my passwords trying to remember which one belongs to that volume. When zulucrypt erases the password in the text box, I sometimes forget which password I tried last.

It would be good to keep the password there even if it were incorrect. A malicious guesser would be using an automated program to crack a volume, so keeping the key in the text box after an incorrect guess doesn't decrease security.

**Comment by mhogomchungu** [comment]
1. Install git version of zuluCrypt.
2. Create a text file named "doNotClearPassword" in ~/zuluCrypt
3.Try to unlock a volume with a wrong key and observe the behavior you want.

**Comment by mhogomchungu** [comment]
Closing this one since the reported issue is now solved.

**Comment by mhogomchungu** [comment]
Version 5.3.0 of zuluCrypt was released yesterday and this option moved and to reset it, open zuluCrypt config file at "~/.config/zuluCrypt/zuluCrypt.conf" and set "ClearPassword=false"
