### ISSUE TITLE
FreeBSD?

### ISSUE THREAD

**Issue by nicgentile** [mhogomchungu/zuluCrypt#72]
Is there a FreeBSD port? I am migrating from Linux to FreeBSD and I need to figure out how to mount the drives.

**Comment by mhogomchungu** [comment]
No,

zuluCrypt depends on cryptsetup[1] primarily and i do not think it has a freebsd port. 

There are also linuxism in zuluCrypt like here[2] that will have to be ported to bsd or neutral APIs but that will come after there is a port of cryptsetup.

[1] https://gitlab.com/cryptsetup/cryptsetup

[2] https://github.com/mhogomchungu/zuluCrypt/blob/074603b742476c262b9a5a0e4831771a48d886f0/zuluCrypt-cli/lib/mountinfo.c#L109

**Comment by mhogomchungu** [comment]
Closing this one since i think the question was sufficiently answered.
