### ISSUE TITLE
Please use standard xdg config directory

### ISSUE THREAD

**Issue by jleclanche** [mhogomchungu/zuluCrypt#74]
https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

Qt5 natively supports this:
https://doc.qt.io/qt-5/qstandardpaths.html

- The config is stored in `$HOME/.zuluCrypt/` instead of `$XDG_CONFIG_HOME/zuluCrypt/` (`QStandardPaths::ConfigLocation`)
- The sockets are created in `$HOME/.zuluCrypt-socket/` instead of `$XDG_RUNTIME_DIR/zuluCrypt/` (`QStandardPaths::RuntimeLocation`)

**Comment by mhogomchungu** [comment]
I think this report will be fixed when zuluCrypt finally move to QSettings. More info is here: https://github.com/mhogomchungu/zuluCrypt/issues/75#issuecomment-338462218

**Comment by mhogomchungu** [comment]
Will move the socket path to appropriate locations later on today

**Comment by jleclanche** [comment]
Awesome :)

**Comment by mhogomchungu** [comment]
Done with this one too.

```$HOME/.zuluCrypt/`` is no longer used.

```$HOME/.zuluCrypt-socket/``` is no longer used when using the project from its GUI components because the runtime path is set from ```QStandardPaths::RuntimeLocation```. 

```$HOME/.zuluCrypt-socket/``` is used a default location when running CLI components because ```$XDG_RUNTIME_DIR/``` is not set in my distro. Will investigate more how to support the runtime path environment variable in CLI.
