### ISSUE TITLE
Suggestion: Change/remove some keyboard shortcuts

### ISSUE THREAD

**Issue by jleclanche** [mhogomchungu/zuluCrypt#77]
I don't think it's wise to have so many keyboard shortcuts in the menus. Keyboard shortcuts should be in general for well-known actions and often-used actions. There already are access keys to all menu items if one wants to navigate with the keyboard.

"Erase Data in a device" for example is mapped to Ctrl+N which is often understood to be "New object". That could be pretty bad. I would unbind it.

Ctrl+X / Ctrl+Z are usually bound to Cut/Undo; I would change the bindings on the open menu. Maybe to Ctrl+O for open file and Ctrl+Shift+O for open device.

Create encrypted file/device are bound to ctrl+a / ctrl+s which is usually "select all" and "save". I would change them to Ctrl+N / Ctrl+Shift+N to match open file/device.

The actions in the volumes menu are all rare enough to all be unbound.

In the favourites menu, "Mount All" is unbound, but it could probably be bound to Ctrl+Shift+M.

Everything in the options menu should probably be unbound.

In the Help menu, I suggest merging About and Contact Info into the same "About" view and unbind it.  Then I suggest creating a "Help" view and bind it to F1; that view would contain the zulucrypt.pdf in rich text or html format instead of pdf (pdf, for many people, isn't accessible) and include the note about header backup. The menu would then look like: "Help (F1); About (Unbound)"

Finally, I would suggest moving "Check for Update" to the primary application menu (currently called zC), and unbind it.

Thoughts?

**Comment by mhogomchungu** [comment]
I have implemented all your suggestions except the shortcuts, They went in about 6 years ago and somebody somewhere is probably depending on them and its not nice to just break their work flow.

**Comment by jleclanche** [comment]
To be honest, I believe there's a lot more concrete overall value in having memorable and unsurprising shortcuts than in not breaking a workflow over very rarely used ones, but I respect your decision either way.
