### ISSUE TITLE
sorry but i need a littele of help pf possible

### ISSUE THREAD

**Issue by ouamar** [mhogomchungu/zuluCrypt#78]
i'm sorry as this is note realted directly to your work but i need some help
i have downloaded data to the primary crypted file that i created using veracrypt and by doing so i damaged the hidden drive 
i found kind of solution here : https://unix.stackexchange.com/questions/126159/tcplay-cannot-mount-filesystem-on-truecrypt-volume-with-hidden-volume-protectio
but i don't know how to do it ,i kept searching until i found your inswer here : https://superuser.com/questions/1261014/how-can-i-open-a-veracrypt-volume-without-mounting-it-ubuntu-16-04
but i couldn't find how to enter my keyfiles ( i'm using just key files ) so i can try th solution mentioned above
thanks and sorry again

**Comment by mhogomchungu** [comment]
So,what you want is to unlock a hidden volume without mounting it to see if you can somehow salvage its file system.

First,make sure you are using zuluCrypt 5.3.0 and then run the following command from root's account.

```
zuluCrypt-cli -O -t vcrypt -d /path/to/your/volume -F /pathtokey1 -F /pathtokey2
```
In summary,use "-F" argument to each of the key files.

You will find the encryption mapper at "/dev/mapper/" and the mapper will start with "zuluCrypt".

**Comment by mhogomchungu** [comment]
I am closing this one for lack of activity.

Please reopen or just comment while is closed if anything comes up.
