### ISSUE TITLE
cannot compile with -DINTERNAL_ZULUPLAY=true

### ISSUE THREAD

**Issue by soredake** [mhogomchungu/zuluCrypt#79]
@mhogomchungu 
[build-log.zip](https://github.com/mhogomchungu/zuluCrypt/files/1464700/build-log.zip)

ZuluCrypt compiles fine when compiling with externally builded zuluplay.

**Comment by mhogomchungu** [comment]
```make -j16 VERBOSE=1```

i suspect the problem is here,you are doing a bit too much parallelism and a dependency somewhere is not being picked properly. It works fine with my "-j4" make option and i tried with "-j16" make option it still build just fine.

Can you try to build without the "-j16" option.

**Comment by soredake** [comment]
Tried with -j1 and still fails
```
libzuluCrypt.so.1.2.0: error: undefined reference to 'dm_task_get_info'
libzuluCrypt.so.1.2.0: error: undefined reference to 'dm_get_next_target'
libzuluCrypt.so.1.2.0: error: undefined reference to 'dm_task_destroy'
libzuluCrypt.so.1.2.0: error: undefined reference to 'dm_task_run'
libzuluCrypt.so.1.2.0: error: undefined reference to 'dm_task_set_name'
libzuluCrypt.so.1.2.0: error: undefined reference to 'dm_task_create'
libzuluCrypt.so.1.2.0: error: undefined reference to 'dm_task_update_nodes'
libzuluCrypt.so.1.2.0: error: undefined reference to 'dm_udev_wait'
libzuluCrypt.so.1.2.0: error: undefined reference to 'dm_task_set_cookie'
libzuluCrypt.so.1.2.0: error: undefined reference to 'dm_task_add_target'
libzuluCrypt.so.1.2.0: error: undefined reference to 'dm_task_set_ro'
libzuluCrypt.so.1.2.0: error: undefined reference to 'dm_task_set_uuid'
libzuluCrypt.so.1.2.0: error: undefined reference to 'uuid_unparse'
libzuluCrypt.so.1.2.0: error: undefined reference to 'uuid_generate'
libzuluCrypt.so.1.2.0: error: undefined reference to 'dm_udev_set_sync_support'
collect2: error: ld returned 1 exit status
```

**Comment by mhogomchungu** [comment]
I think i have fixed the issue in this[1] commit.

Can you update from git and try to build again.

The problem was in zuluplay not dragging in libdevmapper and libuuid when building a static library.


[1] https://github.com/mhogomchungu/zuluCrypt/commit/e33bc6ad24ec2a260cc68cb2f4c0dde3b9ebb421

**Comment by soredake** [comment]
Now it compiles fine, thanks!

**Comment by mhogomchungu** [comment]
New version of zuluCrypt with a fix to reported problem is out: https://github.com/mhogomchungu/zuluCrypt/releases/tag/5.4.0
