### ISSUE TITLE
Building without GUI components results in 'Unknown CMake command "Qt5_WRAP_CPP"' during the configure phase

### ISSUE THREAD

**Issue by pspot2** [mhogomchungu/zuluCrypt#83]
Hi Francis,

while trying to build zuluCrypt-5.4.0 on a headless machine without the GUI components, configure throws the error described below. Building with GUI and Qt5 on another machine with a monitor and KDE works fine. Both machines run the same distro - Gentoo. If this issue is distro-specific and I should open a bug against the package maintainer, please let me know. Thanks.

cmake -C /tmp/portage/app-crypt/zulucrypt-5.4.0/work/zulucrypt-5.4.0_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=lib64 -DNOGNOME=yes -DNOKDE=yes -DNOGUI=yes -DUDEVSUPPORT=yes -DINTERNAL_LXQT_WALLET=true -DINTERNAL_ZULUPLAY=true -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_USER_MAKE_RULES_OVERRIDE=/tmp/portage/app-crypt/zulucrypt-5.4.0/work/zulucrypt-5.4.0_build/gentoo_rules.cmake -DCMAKE_TOOLCHAIN_FILE=/tmp/portage/app-crypt/zulucrypt-5.4.0/work/zulucrypt-5.4.0_build/gentoo_toolchain.cmake  /tmp/portage/app-crypt/zulucrypt-5.4.0/work/zuluCrypt-5.4.0
loading initial cache file /tmp/portage/app-crypt/zulucrypt-5.4.0/work/zulucrypt-5.4.0_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 6.4.0
-- The CXX compiler identification is GNU 6.4.0
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: x86_64-pc-linux-gnu-pkg-config (found version "0.29.2") 
-- Checking for module 'libcryptsetup'
--   Found libcryptsetup, version 1.7.4
-- Checking for module 'blkid'
--   Found blkid, version 2.30.2
-- Checking for module 'devmapper'
--   Found devmapper, version 1.02.119
-- Checking for module 'uuid'
--   Found uuid, version 2.30.2
-- found libdevmapper library at: /usr/lib/libdevmapper.so
-- found uuid library at: /usr/lib/libuuid.so
-- found libcryptsetup library at: /usr/lib/libcryptsetup.so
-- found gcrypt header file: /usr/include/gcrypt.h
-- found gcrypt library: /usr/lib/libgcrypt.so
-- found json.hpp header file at: /tmp/portage/app-crypt/zulucrypt-5.4.0/work/zuluCrypt-5.4.0/external_libraries/json/nlohmann/json.hpp
-- ---------------------------------------------------------------------------
-- internal version of zuluplay will be used to create and open TrueCrypt and VeraCrypt volumes.
-- internal version of zuluplay will be used to create and restore TrueCrypt and VeraCrypt volume headers.
-- ---------------------------------------------------------------------------
-- Checking for module 'devmapper'
--   Found devmapper, version 1.02.119
-- Checking for module 'uuid'
--   Found uuid, version 2.30.2
-- Looking for gcry_kdf_derive in gcrypt
-- Looking for gcry_kdf_derive in gcrypt - found
-- found gcrypt header file: /usr/include/gcrypt.h
-- ---------------------------------------------------------------------------
-- optional functionality that will be build
-- udev support will be enabled
-- zuluplay adds the ability to create truecrypt compatible encrypted containers
-- ---------------------------------------------------------------------------
-- ---------------------------------------------------------------------------
-- optional functionality that will NOT be build
-- GUI front ends,zuluCrypt-gui and zuluMount-gui

-- pwquality library used to measure passphrase strength
-- sources can be found at: https://fedorahosted.org/libpwquality/

-- ---------------------------------------------------------------------------
-- 

-- udev will be consulted when deciding if a volume is system or not.
-- please read "udev_support" file for more information about udev support and associated problems.

-- ---------------------------------------------------------------------------
-- Not building GUI components
-- ---------------------------------------------------------------------------

CMake Error at zuluPolkit/CMakeLists.txt:18 (Qt5_WRAP_CPP):
  Unknown CMake command "Qt5_WRAP_CPP".

-- Configuring incomplete, errors occurred!

**Comment by mhogomchungu** [comment]
I can not reproduce.

Did you run cmake command on a clean build folder? Running cmake command multiple times without first clearing the build folder produces very strange cmake errors.

**Comment by mhogomchungu** [comment]
I am closing this one for lack of info.

Please reopen if you still experience the problem.

**Comment by pspot2** [comment]
Opened a bug against the distro: https://bugs.gentoo.org/647264
