### ISSUE TITLE
Cannot mount file volume after Kubuntu upgrade

### ISSUE THREAD

**Issue by Brigithubert** [mhogomchungu/zuluCrypt#86]
Never touch a running system... I was running zuluMount (4.7.7?) on Kubuntu 16.04 LTS. All my valuable files are stored in a veraCrypt file volume. Well, I thought it'd be cool to upgrade to Zesty.

Now, after the upgrade went smooth, I cannot access my files any more:

> Volume could not be opened with the presented key.

The key is absolutely correct. I have a copy of the container on my NAS -- cannot be encrypted, either. :(

Is this a known problem with (K)Ubuntu upgrades? I am willing to provide any information that may help, solve this issue.

My last idea: Set up Kubuntu 16.04 in a virtual machine and try to access the data...

Thank you for your effort!

**Comment by mhogomchungu** [comment]
What version of zuluCrypt are you running now?

What is the output of the following command: ```sudo zuluCrypt-cli --test```

A recent version of zuluCrypt changed its configuration formal and options have to be reapplied since they were not carried over. Are you sure you are opening your veracrypt volume with the volume type in zuluCrypt GUI set to "VeraCrypt"?

**Comment by Brigithubert** [comment]
Thank you for this extremely quick answer!

First off, mounting the volume in the virtual machine works (zuluMount 4.7.7). That's my personal good news. :)

In Kubuntu 17.04 it doesn't work. Tried the ubuntu package from the repo (5.0.2) as well as the current from github (5.4.0).

Maybe worth mentioning: I even installed veracrypt and tried to mount the container and got pretty much the same result.

Well, I will now start rsyncing the files from my old into a new container.

Output from `sudo zuluCrypt-cli --test`:

> WARNING: "loop" kernel module does not appear to be loaded,
> tests and opening of encrypted containers in files will fail if the module was not built into the kernel
> 
> creating a testing image file
> creating a testing image file
> creating a testing image file
> creating a keyfile
> creating a keyfile
> 
> create a luks type volume using a key: 12345
> PASSED
> 
> check if a luks volume is a luks volume: PASSED
> 
> create luks header backup: PASSED
> 
> restore luks header from backup: PASSED
> 
> create a plain type volume using a key: PASSED
> 
> create a tcrypt type volume using a key: PASSED
> 
> open a plain volume with a key: PASSED
> closing a plain volume: PASSED
> 
> open a plain volume with a keyfile: PASSED
> closing a plain volume: PASSED
> 
> open a tcrypt volume with a key: PASSED
> closing a tcrypt volume: PASSED
> 
> open a plain volume using a plugin: PASSED
> closing a plain volume: PASSED
> 
> open a luks volume with a key: PASSED
> closing a luks volume: PASSED
> 
> open a luks volume with a keyfile: PASSED                                                                                                                                                                                                   
> closing a luks volume: PASSED                                                                                                                                                                                                               
>                                                                                                                                                                                                                                             
> open a luks volume using a plugin: PASSED                                                                                                                                                                                                   
> closing a luks volume: PASSED                                                                                                                                                                                                               
>                                                                                                                                                                                                                                             
> check key slots in use: 30000000                                                                                                                                                                                                            
>                                                                                                                                                                                                                                             
> add a key to a luks volume using a key and a key: PASSED                                                                                                                                                                                    
> add key to luks volume using keyfile and keyfile: PASSED                                                                                                                                                                                    
> add key to luks volume using passphrase and keyfile: PASSED                                                                                                                                                                                 
> add key to luks volume using keyfile and passphrase: PASSED                                                                                                                                                                                 
>                                                                                                                                                                                                                                             
> check key slots in use: 11111000                                                                                                                                                                                                            
>                                                                                                                                                                                                                                             
> remove a key from a luks volume using a key: PASSED                                                                                                                                                                                         
> remove a key from a luks volume using a keyfile: PASSED                                                                                                                                                                                     
> check key slots in use: 01011000                                                                                                                                                                                                            
>                                                                                                                                                                                                                                             
> check if there are no opened mappers: FAILED                                                                                                                                                                                                
> found opened mapper: /dev/mapper/zuluCrypt-1026-NAAN-Testvolume-740851935

**Comment by Brigithubert** [comment]
Sorry, I didn't mean to close this in case you want to analyse this further.

**Comment by mhogomchungu** [comment]
Your system is setup to use what language and on the system that 4.7.7 works is set up to use what language? It could be a locale issue if your password used a character that can not accurately be represented in different locales.

4.7.7 is too old and i do not wish to dig it up to investigate what is going on since you can copy over your data to a new container.
