### ISSUE TITLE
Improved usability for GUI

### ISSUE THREAD

**Issue by HorstBaerbel** [mhogomchungu/zuluCrypt#87]
First of all: Thanks for zuluCrypt, it works really well and I use it regularly on my Ubuntu machine!
I have a suggestion for usabitly improvements thoiugh:
- Mounting a volume can't be done through the zuluCrypt listbox window. It would be convenient to RIGHT-click the empty window and mount a volume or partition (essentially the "Open" and maybe the "Create" menu points).
- Currently, editing mounts in the listbox window is done by left-clicking, which pops up a menu. Imo RIGHT-clicking is much more logical and intuitive here.
- Having some often used menu points in the tray menu ("Mount", "Umount all", etc.) wouldn't hurt either. Currently there's only "Show/hide" and "Exit"...

**Comment by mhogomchungu** [comment]
About your first point, are you aware of the "favorites" feature? Go to "menu->favorites->manage favorites" and add your volume to the favorites list. Then you can easily start the process of unlocking a volume by clicking "menu->favorites->favorites entry". 

About your second point, this is a property of Qt5, Qt4 used to generate a context menu with a right click event but they changed it in Qt5 where a left click is required to generate context menu,

Will look into adding more options in the tray menu.

**Comment by HorstBaerbel** [comment]
Thanks for the tip about the favorites menu. That would be a candidate for the tray menu too...

If you are using a QListWidget or QTableWidget, you could either override contextMenuEvent in a custom class or connect the signal to another object like [here](https://stackoverflow.com/questions/31383519/qt-rightclick-on-qlistwidget-opens-contextmenu-and-delete-item#31385356). In a custom class you could also catch right-click mouse events, but I'd recommend going the context menu way.

**Comment by mhogomchungu** [comment]
Its now possible in the GUI version to invoke the context menu with a right click.

https://github.com/mhogomchungu/zuluCrypt/commit/9b6e2cb740a89b540f89f0b55f863cab9a44f293

**Comment by HorstBaerbel** [comment]
Nice. Thnaks! Will check when the next version is out...

**Comment by mhogomchungu** [comment]
Just added "zC","Open" and "Create" options to the tray icon context menu.

I do not think its possible to do the first one since Qt does not provide an API that registers a click event on a "empty" tableview.

Closing this one since zuluCrypt now does 2/3 requested features and with the remaining one being undoable or beyond my capabilities.
