### ISSUE TITLE
Menu vanishes when closing the mount list window

### ISSUE THREAD

**Issue by HorstBaerbel** [mhogomchungu/zuluCrypt#88]
I use zuluCrypt 5.1.0 on Ubuntu 16.04.03. When I first start zC everything is fine, the menu is there. Then after closing the mount list window for the first time I can still open the zC via the try menu, but the menu is always empty. Restarting zC brings back the menu...

**Comment by mhogomchungu** [comment]
You should update to the latest version(5.4.0). Binary packages for your distribution can be obtained from here: https://mhogomchungu.github.io/zuluCrypt/

This is a known problem between Qt apps and unity's menu. My google searchers have so far being unsuccessful but i remember discussing this with somebody a while ago and seeing the same problem affecting other Qt apps in unity.

**Comment by HorstBaerbel** [comment]
Thanks for the info. The problem persists in 5.4.0 though...

**Comment by mhogomchungu** [comment]
This problem is between Qt and unity and there is nothing i can do on my end.
