### ISSUE TITLE
Codecrypt plugin for zulucrypt

### ISSUE THREAD

**Issue by HulaHoopWhonix** [mhogomchungu/zuluCrypt#93]
Hi. I am interested to see zulucrypt support easy use of codecrypt's post quantum crypto suite analogus to gpg. Codecrypt is available in Debian's archives and is included in our anonymity distro Whonix. Please consider adding support for it.

cc/ @adrelanos

**Comment by mhogomchungu** [comment]
A link or two about the project you are referring to will be appreciated.

**Comment by HulaHoopWhonix** [comment]
My bad:

https://github.com/exaexa/codecrypt
https://e-x-a.org/codecrypt
https://packages.debian.org/stretch/codecrypt

**Comment by mhogomchungu** [comment]
This project seems to be out of scope for zuluCrypt since it does not deal with block device encryption.
