### ISSUE TITLE
Problems on Debian Stretch KDE

### ISSUE THREAD

**Issue by HulaHoopWhonix** [mhogomchungu/zuluCrypt#94]
Hi I tested the Zulucrypt version in Debian stable on the KDE desktop and wanted to report a few bugs. Whenever I try to open the mounted share gwenview is the program used rather than Dolphin, my file explorer. There is no way to change this behavior. When accessing the mount point manually with Dolphin running under kdesudo it keeps reporting "process protocol died unexpectedly" and there is no way to view or edit files in the container. I get the same error with Gwenview.

If you are aware of these problems and already fixed them then please feel free to close this ticket.

**Comment by mhogomchungu** [comment]
What version of zuluCrypt are you using?

**Comment by mhogomchungu** [comment]
A bit of googling and debian 9(stretch) uses version 5.0.2 of zuluCrypt and this version in debian and ubuntu is broken and latest versions of zuluCrypt fixed the problem.

Best thing to do is to completely remove it from your system and then either build the latest version from source or install binary packages i distribute for debian 9 located in the "binary package" section on this[1] page.

[1] https://mhogomchungu.github.io/zuluCrypt/
