### ISSUE TITLE
ZuluMount takes long time if container password is wrong

### ISSUE THREAD

**Issue by khojahay** [mhogomchungu/zuluCrypt#96]
I have veracrypt volume. When trying to mount it using ZM, it takes long time if password was wrong which makes user frustrated. If I use VC, it immediately prompts me that password is wrong in that case.

Can ZM do same as VC where it gives fast prompt in case password is wrong?

Thanks

**Comment by mhogomchungu** [comment]
When unlocking a volume, 99% of the time is spent converting a user provided password into a key and something called "hash function" is one of  the things that are used during this conversion.

By default all hash functions are tried before zuluCrypt/VeraCrypt gives up with "wrong password" error.

One way to reduce the time is to set a hash function causing the application to do ```only one conversion``` and giving up when the password is found to be wrong. VeraCrypt has this option and zuluCrypt does not.

Another way to reduce the time is to do ```all conversions concurrently``` and then check which one is the correct one.  VeraCrypt now do the conversions concurrently while zuluCrypt does it sequentially.

What you are asking is for zuluCrypt to also do the conversions concurrently. Unfortunately, the code that gives zuluCrypt support for TrueCrypt/VeraCrypt support comes from a separate project whose upstream is tcplay[1 and this project is, by all account, abandoned. 

I maintains my own fork of tcplay called zuluplay[2] and zuluCrypt uses this fork. Updating the code base of zuluplay(most of it is unfamiliar to me) to make it do what you are asking for will be too much effort and its not something i want to do at the moment.

[1] https://github.com/bwalex/tc-play
[2] https://github.com/mhogomchungu/zuluplay

**Comment by khojahay** [comment]
Ok

Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
