### ISSUE TITLE
Cannot open a volume without mounting

### ISSUE THREAD

**Issue by rtvd** [mhogomchungu/zuluCrypt#97]
Hello,

TrueCrypt allows to open an encrypted volume as a plain  block device (without mounting anything).

It appears that zuluCrypt does not allow that and assumes that every encrypted volume is mountable.
As a result, it cannot be used with those special volumes which are either not mountable by their nature (as they do not represent file systems) or can be mounted into several places (such as BTRFS file systems).

**Comment by mhogomchungu** [comment]
zuluCrypt from version 5.4.0 offers this ability. It is activated only when zuluCrypt runs privileged and its available with "-O" option.

To unlock a TrueCrypt without mounting it, run a command that looks like below

```
zuluCrypt-cli -O -d /dev/XYZ -t tcrypt
```
