### ISSUE TITLE
Support for Nitrokey Pro?

### ISSUE THREAD

**Issue by comio** [mhogomchungu/zuluCrypt#98]
Hi @mhogomchungu ,
I'm exploring the support for the Nitrokey Pro (www.nitrokey.com) smartcard.
I have not this product but I'm studying to enhance support. 
Give a look at this code:

[nitroluks](https://github.com/artosan/nitroluks/blob/master/src/nitro_luks.c)

should be easy to add a key-ring-like access to "Password Safe" to find the encryption key to your software.

What do you think? I would like to try to add (when I will receive the token). Any suggestion?

ciao

luigi

**Comment by mhogomchungu** [comment]
First thing to find out is if running this program requires root's privileges or not.

Things will be a lot easier if it does not. zuluCrypt currently does not support generic plugins that get input from stdin and support for this use case will have to first be added before this plugin will work.

First thing is first, get the token and see if it this program requires root's password to work or not.

**Comment by HulaHoopWhonix** [comment]
Nitrokey is not open source so I wouldn't bother supporting a closed product that is not auditable. A nice alternative is the Gnuk.

**Comment by mhogomchungu** [comment]
I can not add support for hardware i do not have.

Somebody will have to donate the hardware for me to test.
